# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: a69b5c9977ae

defmodule ArchAstro.SDK.Contract.Channels.ApiTasksChannelTest do
  use ExUnit.Case, async: false
  @moduletag :channel_contract

  test "ApiTasksChannel join_thread facade matches the shared harness" do
    assert :ok =
             ArchAstro.SDK.ContractSupport.verify_channel(
               "ApiTasksChannel",
               "api:tasks:thread:{thread_id}",
               fn socket, push ->
                 assert {:ok, %ArchAstro.SDK.Channel{join_response: %{}} = channel} =
                          ArchAstro.SDK.Channels.ApiTasks.join_thread(socket, "test-id")

                 assert :ok =
                          ArchAstro.SDK.Channels.ApiTasks.subscribe_tasks_updated(channel, self())

                 assert :ok = push.(channel.topic, "tasks_updated")
                 assert_receive {:archastro_channel, ^channel, "tasks_updated", push_payload_0}

                 assert is_struct(
                          push_payload_0,
                          ArchAstro.SDK.Types.ChannelPayloads.ApiTasksChannel.TasksUpdated.Payload
                        )

                 assert :ok = ArchAstro.SDK.Channels.ApiTasks.leave(channel)
                 :ok
               end
             )
  end
end
