# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 4ba8fcd14e05

defmodule ArchAstro.Contract.Channels.ApiActivityFeedChannelTest do
  use ExUnit.Case, async: false
  @moduletag :channel_contract

  test "ApiActivityFeedChannel join_agent facade matches the shared harness" do
    assert :ok =
             ArchAstro.ContractSupport.verify_channel(
               "ApiActivityFeedChannel",
               "api:activity_feed:agent:{agent_id}",
               fn socket, push ->
                 assert {:ok, %ArchAstro.Channel{join_response: %{}} = channel} =
                          ArchAstro.Channels.ApiActivityFeed.join_agent(socket, "test-id")

                 assert {:ok,
                         %ArchAstro.Types.ChannelPayloads.ApiActivityFeedChannel.ListEntries.Response{}} =
                          ArchAstro.Channels.ApiActivityFeed.list_entries(
                            channel,
                            %ArchAstro.Types.ChannelPayloads.ApiActivityFeedChannel.ListEntries.Input{}
                          )

                 assert :ok =
                          ArchAstro.Channels.ApiActivityFeed.subscribe_new_entry(channel, self())

                 assert :ok = push.(channel.topic, "new_entry")
                 assert_receive {:archastro_channel, ^channel, "new_entry", push_payload_0}

                 assert is_struct(
                          push_payload_0,
                          ArchAstro.Types.ChannelPayloads.ApiActivityFeedChannel.NewEntry.Payload
                        )

                 assert :ok = ArchAstro.Channels.ApiActivityFeed.leave(channel)
                 :ok
               end
             )
  end

  test "ApiActivityFeedChannel join_org facade matches the shared harness" do
    assert :ok =
             ArchAstro.ContractSupport.verify_channel(
               "ApiActivityFeedChannel",
               "api:activity_feed:org:{org_id}",
               fn socket, push ->
                 assert {:ok, %ArchAstro.Channel{join_response: %{}} = channel} =
                          ArchAstro.Channels.ApiActivityFeed.join_org(socket, "test-id")

                 assert {:ok,
                         %ArchAstro.Types.ChannelPayloads.ApiActivityFeedChannel.ListEntries.Response{}} =
                          ArchAstro.Channels.ApiActivityFeed.list_entries(
                            channel,
                            %ArchAstro.Types.ChannelPayloads.ApiActivityFeedChannel.ListEntries.Input{}
                          )

                 assert :ok =
                          ArchAstro.Channels.ApiActivityFeed.subscribe_new_entry(channel, self())

                 assert :ok = push.(channel.topic, "new_entry")
                 assert_receive {:archastro_channel, ^channel, "new_entry", push_payload_0}

                 assert is_struct(
                          push_payload_0,
                          ArchAstro.Types.ChannelPayloads.ApiActivityFeedChannel.NewEntry.Payload
                        )

                 assert :ok = ArchAstro.Channels.ApiActivityFeed.leave(channel)
                 :ok
               end
             )
  end
end
