# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 6829ad96af8b

defmodule ArchAstro.SDK.Contract.V1.ActivityFeedTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/activity_feed", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1ActivityFeed.Response{}} =
             ArchAstro.SDK.V1.ActivityFeed.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ActivityFeed.Params{}
             )
  end

  test "GET /api/v1/activity_feed returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.ActivityFeed.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ActivityFeed.Params{}
             )
  end

  test "GET /api/v1/activity_feed returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ActivityFeed.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ActivityFeed.Params{}
             )
  end

  test "GET /api/v1/activity_feed returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.ActivityFeed.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ActivityFeed.Params{}
             )
  end
end
