# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e8ff31aca418

defmodule ArchAstro.Contract.V1.AgentComputersTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "DELETE /api/v1/agent_computers/{computer}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.AgentComputers.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_computers/{computer} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentComputers.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_computers/{computer} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentComputers.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_computers/{computer} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentComputers.delete(client, "test-value")
  end

  test "GET /api/v1/agent_computers/{computer}", %{client: client} do
    assert {:ok, %ArchAstro.Types.AgentComputer{}} =
             ArchAstro.V1.AgentComputers.get(client, "test-value")
  end

  test "GET /api/v1/agent_computers/{computer} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentComputers.get(client, "test-value")
  end

  test "GET /api/v1/agent_computers/{computer} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentComputers.get(client, "test-value")
  end

  test "GET /api/v1/agent_computers/{computer} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentComputers.get(client, "test-value")
  end

  test "POST /api/v1/agent_computers/{computer}/exec", %{client: client} do
    assert {:ok, %ArchAstro.Types.ComputerExecResult{}} =
             ArchAstro.V1.AgentComputers.exec(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AgentComputersComputerExec.Input{
                 command: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_computers/{computer}/exec returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentComputers.exec(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AgentComputersComputerExec.Input{
                 command: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_computers/{computer}/exec returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentComputers.exec(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AgentComputersComputerExec.Input{
                 command: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_computers/{computer}/exec returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentComputers.exec(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AgentComputersComputerExec.Input{
                 command: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_computers/{computer}/exec returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.AgentComputers.exec(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AgentComputersComputerExec.Input{
                 command: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_computers/{computer}/refresh", %{client: client} do
    assert {:ok, %ArchAstro.Types.AgentComputer{}} =
             ArchAstro.V1.AgentComputers.refresh(client, "test-value")
  end

  test "POST /api/v1/agent_computers/{computer}/refresh returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentComputers.refresh(client, "test-value")
  end

  test "POST /api/v1/agent_computers/{computer}/refresh returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentComputers.refresh(client, "test-value")
  end

  test "POST /api/v1/agent_computers/{computer}/refresh returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentComputers.refresh(client, "test-value")
  end
end
