# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 677bae2c7d19

defmodule ArchAstro.SDK.Contract.V1.AgentHealthActionsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/agent_health_actions/{health_action}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentHealthAction{}} =
             ArchAstro.SDK.V1.AgentHealthActions.get(client, "test-value")
  end

  test "GET /api/v1/agent_health_actions/{health_action} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentHealthActions.get(client, "test-value")
  end

  test "GET /api/v1/agent_health_actions/{health_action} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentHealthActions.get(client, "test-value")
  end

  test "GET /api/v1/agent_health_actions/{health_action} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentHealthActions.get(client, "test-value")
  end

  test "POST /api/v1/agent_health_actions/{health_action}/verify", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentHealthAction{}} =
             ArchAstro.SDK.V1.AgentHealthActions.verify(client, "test-value")
  end

  test "POST /api/v1/agent_health_actions/{health_action}/verify returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentHealthActions.verify(client, "test-value")
  end

  test "POST /api/v1/agent_health_actions/{health_action}/verify returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentHealthActions.verify(client, "test-value")
  end

  test "POST /api/v1/agent_health_actions/{health_action}/verify returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentHealthActions.verify(client, "test-value")
  end

  test "POST /api/v1/agent_health_actions/{health_action}/verify returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.AgentHealthActions.verify(client, "test-value")
  end
end
