# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 4abbd810e03f

defmodule ArchAstro.SDK.Contract.V1.AgentSkillsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/agent_skills", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentSkillList{}} =
             ArchAstro.SDK.V1.AgentSkills.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentSkills.Params{}
             )
  end

  test "GET /api/v1/agent_skills returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentSkills.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentSkills.Params{}
             )
  end

  test "GET /api/v1/agent_skills returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentSkills.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentSkills.Params{}
             )
  end

  test "GET /api/v1/agent_skills returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentSkills.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentSkills.Params{}
             )
  end

  test "POST /api/v1/agent_skills", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentSkill{}} =
             ArchAstro.SDK.V1.AgentSkills.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentSkills.Input{
                 agent: "test-value",
                 config: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_skills returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentSkills.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentSkills.Input{
                 agent: "test-value",
                 config: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_skills returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentSkills.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentSkills.Input{
                 agent: "test-value",
                 config: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_skills returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentSkills.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentSkills.Input{
                 agent: "test-value",
                 config: "test-value"
               }
             )
  end

  test "POST /api/v1/agent_skills returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.AgentSkills.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentSkills.Input{
                 agent: "test-value",
                 config: "test-value"
               }
             )
  end

  test "DELETE /api/v1/agent_skills/{agent_skill}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.AgentSkills.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_skills/{agent_skill} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentSkills.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_skills/{agent_skill} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentSkills.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_skills/{agent_skill} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentSkills.delete(client, "test-value")
  end

  test "GET /api/v1/agent_skills/{agent_skill}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentSkill{}} =
             ArchAstro.SDK.V1.AgentSkills.get(client, "test-value")
  end

  test "GET /api/v1/agent_skills/{agent_skill} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentSkills.get(client, "test-value")
  end

  test "GET /api/v1/agent_skills/{agent_skill} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentSkills.get(client, "test-value")
  end

  test "GET /api/v1/agent_skills/{agent_skill} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentSkills.get(client, "test-value")
  end

  test "PATCH /api/v1/agent_skills/{agent_skill}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentSkill{}} =
             ArchAstro.SDK.V1.AgentSkills.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentSkillsAgentSkill.Input{}
             )
  end

  test "PATCH /api/v1/agent_skills/{agent_skill} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentSkills.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentSkillsAgentSkill.Input{}
             )
  end

  test "PATCH /api/v1/agent_skills/{agent_skill} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentSkills.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentSkillsAgentSkill.Input{}
             )
  end

  test "PATCH /api/v1/agent_skills/{agent_skill} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentSkills.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentSkillsAgentSkill.Input{}
             )
  end

  test "PATCH /api/v1/agent_skills/{agent_skill} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.AgentSkills.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentSkillsAgentSkill.Input{}
             )
  end

  test "POST /api/v1/agent_skills/{agent_skill}/activate", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentSkill{}} =
             ArchAstro.SDK.V1.AgentSkills.activate(client, "test-value")
  end

  test "POST /api/v1/agent_skills/{agent_skill}/activate returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentSkills.activate(client, "test-value")
  end

  test "POST /api/v1/agent_skills/{agent_skill}/activate returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentSkills.activate(client, "test-value")
  end

  test "POST /api/v1/agent_skills/{agent_skill}/activate returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentSkills.activate(client, "test-value")
  end

  test "POST /api/v1/agent_skills/{agent_skill}/deactivate", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentSkill{}} =
             ArchAstro.SDK.V1.AgentSkills.deactivate(client, "test-value")
  end

  test "POST /api/v1/agent_skills/{agent_skill}/deactivate returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentSkills.deactivate(client, "test-value")
  end

  test "POST /api/v1/agent_skills/{agent_skill}/deactivate returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentSkills.deactivate(client, "test-value")
  end

  test "POST /api/v1/agent_skills/{agent_skill}/deactivate returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentSkills.deactivate(client, "test-value")
  end
end
