# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 7781a9156a2d

defmodule ArchAstro.Contract.V1.AgentToolsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/agent_tools", %{client: client} do
    assert {:ok, %ArchAstro.Types.AgentToolListResponse{}} =
             ArchAstro.V1.AgentTools.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1AgentTools.Params{}
             )
  end

  test "GET /api/v1/agent_tools returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentTools.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1AgentTools.Params{}
             )
  end

  test "GET /api/v1/agent_tools returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentTools.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1AgentTools.Params{}
             )
  end

  test "GET /api/v1/agent_tools returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentTools.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1AgentTools.Params{}
             )
  end

  test "GET /api/v1/agent_tools/catalog", %{client: client} do
    assert {:ok, items} = ArchAstro.V1.AgentTools.catalog(client)
    assert is_list(items)
  end

  test "GET /api/v1/agent_tools/catalog returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.AgentTools.catalog(client)
  end

  test "GET /api/v1/agent_tools/catalog returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)
    assert {:error, %ArchAstro.Error{status: 403}} = ArchAstro.V1.AgentTools.catalog(client)
  end

  test "DELETE /api/v1/agent_tools/{tool}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.AgentTools.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_tools/{tool} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentTools.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_tools/{tool} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentTools.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_tools/{tool} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentTools.delete(client, "test-value")
  end

  test "GET /api/v1/agent_tools/{tool}", %{client: client} do
    assert {:ok, %ArchAstro.Types.AgentTool{}} = ArchAstro.V1.AgentTools.get(client, "test-value")
  end

  test "GET /api/v1/agent_tools/{tool} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentTools.get(client, "test-value")
  end

  test "GET /api/v1/agent_tools/{tool} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentTools.get(client, "test-value")
  end

  test "GET /api/v1/agent_tools/{tool} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentTools.get(client, "test-value")
  end

  test "PATCH /api/v1/agent_tools/{tool}", %{client: client} do
    assert {:ok, %ArchAstro.Types.AgentTool{}} =
             ArchAstro.V1.AgentTools.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1AgentToolsTool.Input{}
             )
  end

  test "PATCH /api/v1/agent_tools/{tool} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentTools.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1AgentToolsTool.Input{}
             )
  end

  test "PATCH /api/v1/agent_tools/{tool} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentTools.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1AgentToolsTool.Input{}
             )
  end

  test "PATCH /api/v1/agent_tools/{tool} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentTools.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1AgentToolsTool.Input{}
             )
  end

  test "PATCH /api/v1/agent_tools/{tool} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.AgentTools.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1AgentToolsTool.Input{}
             )
  end

  test "POST /api/v1/agent_tools/{tool}/activate", %{client: client} do
    assert {:ok, %ArchAstro.Types.AgentTool{}} =
             ArchAstro.V1.AgentTools.activate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/activate returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentTools.activate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/activate returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentTools.activate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/activate returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentTools.activate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/activate returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.AgentTools.activate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/deactivate", %{client: client} do
    assert {:ok, %ArchAstro.Types.AgentTool{}} =
             ArchAstro.V1.AgentTools.deactivate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/deactivate returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.AgentTools.deactivate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/deactivate returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.AgentTools.deactivate(client, "test-value")
  end

  test "POST /api/v1/agent_tools/{tool}/deactivate returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.AgentTools.deactivate(client, "test-value")
  end
end
