# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 68b6b12ba355

defmodule ArchAstro.SDK.Contract.V1.AgentRoutineRunsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/agent_routine_runs", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentRoutineRunListResponse{}} =
             ArchAstro.SDK.V1.AgentRoutineRuns.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentRoutineRuns.Params{}
             )
  end

  test "GET /api/v1/agent_routine_runs returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.AgentRoutineRuns.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentRoutineRuns.Params{}
             )
  end

  test "GET /api/v1/agent_routine_runs returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentRoutineRuns.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentRoutineRuns.Params{}
             )
  end

  test "GET /api/v1/agent_routine_runs returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentRoutineRuns.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentRoutineRuns.Params{}
             )
  end

  test "GET /api/v1/agent_routine_runs returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentRoutineRuns.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentRoutineRuns.Params{}
             )
  end

  @tag :channel_contract
  test "GET /api/v1/agent_routine_runs/{agent_routine_run}/stream", %{client: client} do
    _ = client

    assert {:ok, events} =
             ArchAstro.SDK.ContractSupport.verify_stream(
               "GET /api/v1/agent_routine_runs/{agent_routine_run}/stream",
               ["run_update"],
               fn client ->
                 ArchAstro.SDK.V1.AgentRoutineRuns.stream(client, "test-value")
               end
             )

    assert %ArchAstro.SDK.SSE.Event{event: "run_update", data: event_data_0} = Enum.at(events, 0)
    assert is_struct(event_data_0, ArchAstro.SDK.Types.AgentRoutineRun)

    assert :ok =
             ArchAstro.SDK.ContractSupport.verify_stream_error(
               "GET /api/v1/agent_routine_runs/{agent_routine_run}/stream",
               fn client ->
                 ArchAstro.SDK.V1.AgentRoutineRuns.stream(client, "test-value")
               end
             )
  end
end
