# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 73d613418b35

defmodule ArchAstro.SDK.Contract.V1.AgentEnvVarsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "DELETE /api/v1/agent_env_vars/{env_var}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.AgentEnvVars.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_env_vars/{env_var} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentEnvVars.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_env_vars/{env_var} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentEnvVars.delete(client, "test-value")
  end

  test "DELETE /api/v1/agent_env_vars/{env_var} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentEnvVars.delete(client, "test-value")
  end

  test "GET /api/v1/agent_env_vars/{env_var}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentEnvVarMasked{}} =
             ArchAstro.SDK.V1.AgentEnvVars.get(client, "test-value")
  end

  test "GET /api/v1/agent_env_vars/{env_var} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentEnvVars.get(client, "test-value")
  end

  test "GET /api/v1/agent_env_vars/{env_var} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentEnvVars.get(client, "test-value")
  end

  test "GET /api/v1/agent_env_vars/{env_var} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentEnvVars.get(client, "test-value")
  end

  test "PATCH /api/v1/agent_env_vars/{env_var}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentEnvVarMasked{}} =
             ArchAstro.SDK.V1.AgentEnvVars.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentEnvVarsEnvVar.Input{}
             )
  end

  test "PATCH /api/v1/agent_env_vars/{env_var} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.AgentEnvVars.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentEnvVarsEnvVar.Input{}
             )
  end

  test "PATCH /api/v1/agent_env_vars/{env_var} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.AgentEnvVars.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentEnvVarsEnvVar.Input{}
             )
  end

  test "PATCH /api/v1/agent_env_vars/{env_var} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.AgentEnvVars.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentEnvVarsEnvVar.Input{}
             )
  end

  test "PATCH /api/v1/agent_env_vars/{env_var} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.AgentEnvVars.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentEnvVarsEnvVar.Input{}
             )
  end
end
