# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: a1ba8b8165c0

defmodule ArchAstro.SDK.Contract.V1.AgentsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/agents", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentListResponse{}} =
             ArchAstro.SDK.V1.Agents.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1Agents.Params{}
             )
  end

  test "GET /api/v1/agents returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1Agents.Params{}
             )
  end

  test "GET /api/v1/agents returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1Agents.Params{}
             )
  end

  test "POST /api/v1/agents", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentCreateResponse{}} =
             ArchAstro.SDK.V1.Agents.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Agents.Input{}
             )
  end

  test "POST /api/v1/agents returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Agents.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Agents.Input{}
             )
  end

  test "POST /api/v1/agents returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Agents.Input{}
             )
  end

  test "POST /api/v1/agents returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Agents.Input{}
             )
  end

  test "POST /api/v1/agents returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Agents.Input{}
             )
  end

  test "POST /api/v1/agents returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.Agents.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Agents.Input{}
             )
  end

  test "POST /api/v1/agents returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Agents.Input{}
             )
  end

  test "DELETE /api/v1/agents/{agent}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.Agents.delete(client, "test-value")
  end

  test "DELETE /api/v1/agents/{agent} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.delete(client, "test-value")
  end

  test "DELETE /api/v1/agents/{agent} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.delete(client, "test-value")
  end

  test "DELETE /api/v1/agents/{agent} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.delete(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Agent{}} = ArchAstro.SDK.V1.Agents.get(client, "test-value")
  end

  test "GET /api/v1/agents/{agent} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.get(client, "test-value")
  end

  test "GET /api/v1/agents/{agent} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.get(client, "test-value")
  end

  test "GET /api/v1/agents/{agent} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.get(client, "test-value")
  end

  test "PATCH /api/v1/agents/{agent}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Agent{}} =
             ArchAstro.SDK.V1.Agents.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgent.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgent.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgent.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgent.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgent.Input{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_health_actions", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.HealthActionListResponse{}} =
             ArchAstro.SDK.V1.Agents.agent_health_actions(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentHealthActions.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_health_actions returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.agent_health_actions(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentHealthActions.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_health_actions returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.agent_health_actions(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentHealthActions.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_health_actions returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.agent_health_actions(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentHealthActions.Params{}
             )
  end

  test "POST /api/v1/agents/{agent}/agent_routines", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentRoutine{}} =
             ArchAstro.SDK.V1.Agents.agent_routines(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentRoutines.Input{
                 handler_type: "test-value",
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_routines returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.agent_routines(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentRoutines.Input{
                 handler_type: "test-value",
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_routines returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.agent_routines(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentRoutines.Input{
                 handler_type: "test-value",
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_routines returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.agent_routines(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentRoutines.Input{
                 handler_type: "test-value",
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_routines returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.agent_routines(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentRoutines.Input{
                 handler_type: "test-value",
                 name: "test-name"
               }
             )
  end

  test "GET /api/v1/agents/{agent}/export", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentExport{}} =
             ArchAstro.SDK.V1.Agents.export(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentExport.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/export returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.export(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentExport.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/export returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.export(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentExport.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/export returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.export(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentExport.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/health", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentHealth{}} =
             ArchAstro.SDK.V1.Agents.health(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/health returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.health(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/health returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.health(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/health returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.health(client, "test-value")
  end

  test "POST /api/v1/agents/{agent}/search", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentSearch.Response{}} =
             ArchAstro.SDK.V1.Agents.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentSearch.Input{query: "test-value"}
             )
  end

  test "POST /api/v1/agents/{agent}/search returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentSearch.Input{query: "test-value"}
             )
  end

  test "POST /api/v1/agents/{agent}/search returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentSearch.Input{query: "test-value"}
             )
  end

  test "POST /api/v1/agents/{agent}/search returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentSearch.Input{query: "test-value"}
             )
  end

  test "POST /api/v1/agents/{agent}/threads", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Thread{}} =
             ArchAstro.SDK.V1.Agents.threads(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/agents/{agent}/threads returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.threads(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/agents/{agent}/threads returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.threads(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/agents/{agent}/threads returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.threads(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/agents/{agent}/threads returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.threads(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/agents/{agent}/upgrade", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentUpgradeResponse{}} =
             ArchAstro.SDK.V1.Agents.upgrade(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentUpgrade.Input{}
             )
  end

  test "POST /api/v1/agents/{agent}/upgrade returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Agents.upgrade(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentUpgrade.Input{}
             )
  end

  test "POST /api/v1/agents/{agent}/upgrade returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.upgrade(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentUpgrade.Input{}
             )
  end

  test "POST /api/v1/agents/{agent}/upgrade returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.upgrade(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentUpgrade.Input{}
             )
  end

  test "POST /api/v1/agents/{agent}/upgrade returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.upgrade(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentUpgrade.Input{}
             )
  end

  test "POST /api/v1/agents/{agent}/upgrade returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.Agents.upgrade(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentUpgrade.Input{}
             )
  end

  test "POST /api/v1/agents/{agent}/upgrade returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.upgrade(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentUpgrade.Input{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_computers", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentComputerListResponse{}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_computers returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_computers returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_computers returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.list(client, "test-value")
  end

  test "POST /api/v1/agents/{agent}/agent_computers", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentComputer{}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentComputers.Input{
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_computers returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentComputers.Input{
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_computers returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentComputers.Input{
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_computers returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentComputers.Input{
                 name: "test-name"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_computers returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.AgentComputers.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentComputers.Input{
                 name: "test-name"
               }
             )
  end

  test "GET /api/v1/agents/{agent}/agent_env_vars", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentEnvVarMaskedList{}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_env_vars returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_env_vars returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_env_vars returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.list(client, "test-value")
  end

  test "POST /api/v1/agents/{agent}/agent_env_vars", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentEnvVarMasked{}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentEnvVars.Input{
                 key: "test-key",
                 value: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_env_vars returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentEnvVars.Input{
                 key: "test-key",
                 value: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_env_vars returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentEnvVars.Input{
                 key: "test-key",
                 value: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_env_vars returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentEnvVars.Input{
                 key: "test-key",
                 value: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_env_vars returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.AgentEnvVars.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentEnvVars.Input{
                 key: "test-key",
                 value: "test-value"
               }
             )
  end

  test "GET /api/v1/agents/{agent}/agent_installations", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.InstallationListResponse{}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_installations returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_installations returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.list(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_installations returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.list(client, "test-value")
  end

  test "POST /api/v1/agents/{agent}/agent_installations", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Installation{}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentInstallations.Input{
                 kind: "test"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_installations returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentInstallations.Input{
                 kind: "test"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_installations returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentInstallations.Input{
                 kind: "test"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_installations returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentInstallations.Input{
                 kind: "test"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/agent_installations returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentInstallations.Input{
                 kind: "test"
               }
             )
  end

  test "GET /api/v1/agents/{agent}/agent_installations/kinds", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.InstallationKindListResponse{}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.kinds(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_installations/kinds returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.kinds(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_installations/kinds returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentInstallations.kinds(client, "test-value")
  end

  test "GET /api/v1/agents/{agent}/agent_tools", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentToolListResponse{}} =
             ArchAstro.SDK.V1.Agents.AgentTools.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentTools.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_tools returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentTools.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentTools.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_tools returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentTools.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentTools.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_tools returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentTools.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentTools.Params{}
             )
  end

  test "POST /api/v1/agents/{agent}/agent_tools", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentTool{}} =
             ArchAstro.SDK.V1.Agents.AgentTools.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentTools.Input{kind: "test"}
             )
  end

  test "POST /api/v1/agents/{agent}/agent_tools returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentTools.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentTools.Input{kind: "test"}
             )
  end

  test "POST /api/v1/agents/{agent}/agent_tools returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentTools.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentTools.Input{kind: "test"}
             )
  end

  test "POST /api/v1/agents/{agent}/agent_tools returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentTools.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentTools.Input{kind: "test"}
             )
  end

  test "POST /api/v1/agents/{agent}/agent_tools returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.AgentTools.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentAgentTools.Input{kind: "test"}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_working_memory", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.WorkingMemoryEntryListResponse{}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentWorkingMemory.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_working_memory returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentWorkingMemory.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_working_memory returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentWorkingMemory.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/agent_working_memory returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentAgentWorkingMemory.Params{}
             )
  end

  test "DELETE /api/v1/agents/{agent}/agent_working_memory/{entry}", %{client: client} do
    assert {:ok, :ok} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/agents/{agent}/agent_working_memory/{entry} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/agents/{agent}/agent_working_memory/{entry} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/agents/{agent}/agent_working_memory/{entry} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.delete(client, "test-value", "test-value")
  end

  test "PATCH /api/v1/agents/{agent}/agent_working_memory/{entry}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.WorkingMemoryEntry{}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgentAgentWorkingMemoryEntry.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent}/agent_working_memory/{entry} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgentAgentWorkingMemoryEntry.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent}/agent_working_memory/{entry} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgentAgentWorkingMemoryEntry.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent}/agent_working_memory/{entry} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgentAgentWorkingMemoryEntry.Input{}
             )
  end

  test "PATCH /api/v1/agents/{agent}/agent_working_memory/{entry} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.AgentWorkingMemory.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1AgentsAgentAgentWorkingMemoryEntry.Input{}
             )
  end

  test "GET /api/v1/agents/{agent}/schedules", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentSchedules.Response{}} =
             ArchAstro.SDK.V1.Agents.Schedules.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentSchedules.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/schedules returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Agents.Schedules.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentSchedules.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/schedules returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.Schedules.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentSchedules.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/schedules returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.Schedules.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentSchedules.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/schedules/{schedule}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.AgentSchedule{}} =
             ArchAstro.SDK.V1.Agents.Schedules.get(client, "test-value", "test-value")
  end

  test "GET /api/v1/agents/{agent}/schedules/{schedule} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.Schedules.get(client, "test-value", "test-value")
  end

  test "GET /api/v1/agents/{agent}/schedules/{schedule} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.Schedules.get(client, "test-value", "test-value")
  end

  test "GET /api/v1/agents/{agent}/schedules/{schedule} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.Schedules.get(client, "test-value", "test-value")
  end

  test "GET /api/v1/agents/{agent}/work_items", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.WorkflowWorkItemList{}} =
             ArchAstro.SDK.V1.Agents.WorkItems.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentWorkItems.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/work_items returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Agents.WorkItems.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentWorkItems.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/work_items returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.WorkItems.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentWorkItems.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/work_items returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.WorkItems.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentWorkItems.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/work_items returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.WorkItems.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentWorkItems.Params{}
             )
  end

  test "GET /api/v1/agents/{agent}/work_items returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.WorkItems.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1AgentsAgentWorkItems.Params{}
             )
  end

  test "POST /api/v1/agents/{agent}/work_items/claim", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.WorkflowWorkItemClaim{}} =
             ArchAstro.SDK.V1.Agents.WorkItems.claim(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentWorkItemsClaim.Input{
                 lease_owner: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/work_items/claim returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Agents.WorkItems.claim(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentWorkItemsClaim.Input{
                 lease_owner: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/work_items/claim returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Agents.WorkItems.claim(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentWorkItemsClaim.Input{
                 lease_owner: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/work_items/claim returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Agents.WorkItems.claim(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentWorkItemsClaim.Input{
                 lease_owner: "test-value"
               }
             )
  end

  test "POST /api/v1/agents/{agent}/work_items/claim returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Agents.WorkItems.claim(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1AgentsAgentWorkItemsClaim.Input{
                 lease_owner: "test-value"
               }
             )
  end
end
