# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 94c855a3235f

defmodule ArchAstro.Contract.V1.AiTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/ai/chat/models", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1AiChatModels.Response{}} =
             ArchAstro.V1.Ai.Chat.models(client)
  end

  test "GET /api/v1/ai/chat/models returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.Ai.Chat.models(client)
  end

  test "POST /api/v1/ai/chat/completions", %{client: client} do
    assert {:ok, %ArchAstro.Types.AICompletionResult{}} =
             ArchAstro.V1.Ai.Chat.Completions.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input{
                 messages: [],
                 opts: %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input.Nested.Opts{
                   model: "test-model"
                 }
               }
             )
  end

  test "POST /api/v1/ai/chat/completions returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Ai.Chat.Completions.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input{
                 messages: [],
                 opts: %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input.Nested.Opts{
                   model: "test-model"
                 }
               }
             )
  end

  test "POST /api/v1/ai/chat/completions returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Ai.Chat.Completions.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input{
                 messages: [],
                 opts: %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input.Nested.Opts{
                   model: "test-model"
                 }
               }
             )
  end

  test "POST /api/v1/ai/chat/completions returns 402" do
    client = ArchAstro.ContractSupport.error_client(402)

    assert {:error, %ArchAstro.Error{status: 402}} =
             ArchAstro.V1.Ai.Chat.Completions.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input{
                 messages: [],
                 opts: %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input.Nested.Opts{
                   model: "test-model"
                 }
               }
             )
  end

  test "POST /api/v1/ai/chat/completions returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Ai.Chat.Completions.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input{
                 messages: [],
                 opts: %ArchAstro.Types.Operations.PostApiV1AiChatCompletions.Input.Nested.Opts{
                   model: "test-model"
                 }
               }
             )
  end

  @tag :channel_contract
  test "POST /api/v1/ai/chat/completions/stream", %{client: client} do
    _ = client

    assert {:ok, events} =
             ArchAstro.ContractSupport.verify_stream(
               "POST /api/v1/ai/chat/completions/stream",
               [
                 "done",
                 "error",
                 "message_complete",
                 "message_delta",
                 "thinking_delta",
                 "tool_call_delta",
                 "tool_result"
               ],
               fn client ->
                 ArchAstro.V1.Ai.Chat.Completions.Stream.create(
                   client,
                   %ArchAstro.Types.Operations.PostApiV1AiChatCompletionsStream.Input{
                     messages: [],
                     opts:
                       %ArchAstro.Types.Operations.PostApiV1AiChatCompletionsStream.Input.Nested.Opts{
                         model: "test-model"
                       }
                   }
                 )
               end
             )

    assert %ArchAstro.SSE.Event{event: "done", data: event_data_0} = Enum.at(events, 0)
    assert is_struct(event_data_0, ArchAstro.Types.AIChatStreamDone)
    assert %ArchAstro.SSE.Event{event: "error", data: event_data_1} = Enum.at(events, 1)
    assert is_struct(event_data_1, ArchAstro.Types.AIChatStreamError)
    assert %ArchAstro.SSE.Event{event: "message_complete", data: event_data_2} = Enum.at(events, 2)
    assert is_struct(event_data_2, ArchAstro.Types.AIChatStreamMessageComplete)
    assert %ArchAstro.SSE.Event{event: "message_delta", data: event_data_3} = Enum.at(events, 3)
    assert is_struct(event_data_3, ArchAstro.Types.AIChatStreamMessageDelta)
    assert %ArchAstro.SSE.Event{event: "thinking_delta", data: event_data_4} = Enum.at(events, 4)
    assert is_struct(event_data_4, ArchAstro.Types.AIChatStreamThinkingDelta)
    assert %ArchAstro.SSE.Event{event: "tool_call_delta", data: event_data_5} = Enum.at(events, 5)
    assert is_struct(event_data_5, ArchAstro.Types.AIChatStreamToolCallDelta)
    assert %ArchAstro.SSE.Event{event: "tool_result", data: event_data_6} = Enum.at(events, 6)
    assert is_struct(event_data_6, ArchAstro.Types.AIChatStreamToolResult)

    assert :ok =
             ArchAstro.ContractSupport.verify_stream_error(
               "POST /api/v1/ai/chat/completions/stream",
               fn client ->
                 ArchAstro.V1.Ai.Chat.Completions.Stream.create(
                   client,
                   %ArchAstro.Types.Operations.PostApiV1AiChatCompletionsStream.Input{
                     messages: [],
                     opts:
                       %ArchAstro.Types.Operations.PostApiV1AiChatCompletionsStream.Input.Nested.Opts{
                         model: "test-model"
                       }
                   }
                 )
               end
             )
  end

  test "POST /api/v1/ai/embedding/similarity_comparison", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.PostApiV1AiEmbeddingSimilarityComparison.Response{}} =
             ArchAstro.V1.Ai.Embedding.similarity_comparison(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiEmbeddingSimilarityComparison.Input{
                 text_a: "test-value",
                 text_b: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/embedding/similarity_comparison returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Ai.Embedding.similarity_comparison(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiEmbeddingSimilarityComparison.Input{
                 text_a: "test-value",
                 text_b: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/embedding/similarity_comparison returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Ai.Embedding.similarity_comparison(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiEmbeddingSimilarityComparison.Input{
                 text_a: "test-value",
                 text_b: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/embedding/similarity_comparison returns 402" do
    client = ArchAstro.ContractSupport.error_client(402)

    assert {:error, %ArchAstro.Error{status: 402}} =
             ArchAstro.V1.Ai.Embedding.similarity_comparison(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiEmbeddingSimilarityComparison.Input{
                 text_a: "test-value",
                 text_b: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/embedding/similarity_comparison returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Ai.Embedding.similarity_comparison(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiEmbeddingSimilarityComparison.Input{
                 text_a: "test-value",
                 text_b: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/image/edits", %{client: client} do
    assert {:ok, %ArchAstro.Types.AIImageResult{}} =
             ArchAstro.V1.Ai.Image.edits(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageEdits.Input{
                 images: [],
                 prompt: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/image/edits returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Ai.Image.edits(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageEdits.Input{
                 images: [],
                 prompt: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/image/edits returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Ai.Image.edits(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageEdits.Input{
                 images: [],
                 prompt: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/image/edits returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Ai.Image.edits(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageEdits.Input{
                 images: [],
                 prompt: "test-value"
               }
             )
  end

  test "POST /api/v1/ai/image/generations", %{client: client} do
    assert {:ok, %ArchAstro.Types.AIImageResult{}} =
             ArchAstro.V1.Ai.Image.generations(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageGenerations.Input{prompt: "test-value"}
             )
  end

  test "POST /api/v1/ai/image/generations returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Ai.Image.generations(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageGenerations.Input{prompt: "test-value"}
             )
  end

  test "POST /api/v1/ai/image/generations returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Ai.Image.generations(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageGenerations.Input{prompt: "test-value"}
             )
  end

  test "POST /api/v1/ai/image/generations returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Ai.Image.generations(
               client,
               %ArchAstro.Types.Operations.PostApiV1AiImageGenerations.Input{prompt: "test-value"}
             )
  end

  test "GET /api/v1/ai/image/models", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1AiImageModels.Response{}} =
             ArchAstro.V1.Ai.Image.models(client)
  end

  test "GET /api/v1/ai/image/models returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.Ai.Image.models(client)
  end
end
