# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 55c67abb8f0e

defmodule ArchAstro.Contract.V1.AutomationsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "POST /api/v1/automations/{automation}/invoke", %{client: client} do
    assert {:ok, %ArchAstro.Types.AutomationRun{}} =
             ArchAstro.V1.Automations.invoke(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AutomationsAutomationInvoke.Input{}
             )
  end

  test "POST /api/v1/automations/{automation}/invoke returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Automations.invoke(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AutomationsAutomationInvoke.Input{}
             )
  end

  test "POST /api/v1/automations/{automation}/invoke returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Automations.invoke(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AutomationsAutomationInvoke.Input{}
             )
  end

  test "POST /api/v1/automations/{automation}/invoke returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Automations.invoke(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AutomationsAutomationInvoke.Input{}
             )
  end

  test "POST /api/v1/automations/{automation}/invoke returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Automations.invoke(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AutomationsAutomationInvoke.Input{}
             )
  end

  test "POST /api/v1/automations/{automation}/invoke returns 409" do
    client = ArchAstro.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.Error{status: 409}} =
             ArchAstro.V1.Automations.invoke(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AutomationsAutomationInvoke.Input{}
             )
  end

  test "POST /api/v1/automations/{automation}/invoke returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Automations.invoke(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1AutomationsAutomationInvoke.Input{}
             )
  end
end
