# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: a4ea813eb0f1

defmodule ArchAstro.Contract.V1.CustomObjectsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/custom_objects", %{client: client} do
    assert {:ok, %ArchAstro.Types.CustomObjectListResponse{}} =
             ArchAstro.V1.CustomObjects.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1CustomObjects.Params{}
             )
  end

  test "GET /api/v1/custom_objects returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.CustomObjects.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1CustomObjects.Params{}
             )
  end

  test "GET /api/v1/custom_objects returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.CustomObjects.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1CustomObjects.Params{}
             )
  end

  test "GET /api/v1/custom_objects returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.CustomObjects.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1CustomObjects.Params{}
             )
  end

  test "POST /api/v1/custom_objects", %{client: client} do
    assert {:ok, %ArchAstro.Types.CustomObject{}} =
             ArchAstro.V1.CustomObjects.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1CustomObjects.Input{}
             )
  end

  test "POST /api/v1/custom_objects returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.CustomObjects.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1CustomObjects.Input{}
             )
  end

  test "POST /api/v1/custom_objects returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.CustomObjects.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1CustomObjects.Input{}
             )
  end

  test "POST /api/v1/custom_objects returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.CustomObjects.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1CustomObjects.Input{}
             )
  end

  test "POST /api/v1/custom_objects returns 409" do
    client = ArchAstro.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.Error{status: 409}} =
             ArchAstro.V1.CustomObjects.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1CustomObjects.Input{}
             )
  end

  test "POST /api/v1/custom_objects returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.CustomObjects.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1CustomObjects.Input{}
             )
  end

  test "DELETE /api/v1/custom_objects/{object}", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.DeleteApiV1CustomObjectsObject.Response{}} =
             ArchAstro.V1.CustomObjects.delete(client, "test-value")
  end

  test "DELETE /api/v1/custom_objects/{object} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.CustomObjects.delete(client, "test-value")
  end

  test "DELETE /api/v1/custom_objects/{object} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.CustomObjects.delete(client, "test-value")
  end

  test "GET /api/v1/custom_objects/{object}", %{client: client} do
    assert {:ok, %ArchAstro.Types.CustomObject{}} =
             ArchAstro.V1.CustomObjects.get(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1CustomObjectsObject.Params{}
             )
  end

  test "GET /api/v1/custom_objects/{object} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.CustomObjects.get(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1CustomObjectsObject.Params{}
             )
  end

  test "GET /api/v1/custom_objects/{object} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.CustomObjects.get(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1CustomObjectsObject.Params{}
             )
  end

  test "PUT /api/v1/custom_objects/{object}", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.PutApiV1CustomObjectsObject.Response{}} =
             ArchAstro.V1.CustomObjects.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1CustomObjectsObject.Input{}
             )
  end

  test "PUT /api/v1/custom_objects/{object} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.CustomObjects.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1CustomObjectsObject.Input{}
             )
  end

  test "PUT /api/v1/custom_objects/{object} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.CustomObjects.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1CustomObjectsObject.Input{}
             )
  end

  test "PUT /api/v1/custom_objects/{object} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.CustomObjects.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1CustomObjectsObject.Input{}
             )
  end

  test "PUT /api/v1/custom_objects/{object} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.CustomObjects.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1CustomObjectsObject.Input{}
             )
  end
end
