# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: b0377b2dbbf2

defmodule ArchAstro.SDK.Contract.V1.ExternalObjectCapabilitiesTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "DELETE /api/v1/external_object_capabilities", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.ExternalObjectCapabilities.remove(client)
  end

  test "DELETE /api/v1/external_object_capabilities returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.remove(client)
  end

  test "DELETE /api/v1/external_object_capabilities returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.remove(client)
  end

  test "DELETE /api/v1/external_object_capabilities returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.remove(client)
  end

  test "POST /api/v1/external_object_capabilities", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.RuntimeCapability{}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjectCapabilities.Input{
                 bindings: %{},
                 subject: "test-value"
               }
             )
  end

  test "POST /api/v1/external_object_capabilities returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjectCapabilities.Input{
                 bindings: %{},
                 subject: "test-value"
               }
             )
  end

  test "POST /api/v1/external_object_capabilities returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjectCapabilities.Input{
                 bindings: %{},
                 subject: "test-value"
               }
             )
  end

  test "POST /api/v1/external_object_capabilities returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjectCapabilities.Input{
                 bindings: %{},
                 subject: "test-value"
               }
             )
  end

  test "POST /api/v1/external_object_capabilities returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjectCapabilities.Input{
                 bindings: %{},
                 subject: "test-value"
               }
             )
  end

  test "POST /api/v1/external_object_capabilities returns 502" do
    client = ArchAstro.SDK.ContractSupport.error_client(502)

    assert {:error, %ArchAstro.SDK.Error{status: 502}} =
             ArchAstro.SDK.V1.ExternalObjectCapabilities.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjectCapabilities.Input{
                 bindings: %{},
                 subject: "test-value"
               }
             )
  end
end
