# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 2a5506a2265c

defmodule ArchAstro.SDK.Contract.V1.ExternalObjectsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/external_objects", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1ExternalObjects.Response{}} =
             ArchAstro.SDK.V1.ExternalObjects.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ExternalObjects.Params{}
             )
  end

  test "GET /api/v1/external_objects returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.ExternalObjects.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ExternalObjects.Params{}
             )
  end

  test "GET /api/v1/external_objects returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ExternalObjects.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ExternalObjects.Params{}
             )
  end

  test "GET /api/v1/external_objects returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.ExternalObjects.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1ExternalObjects.Params{}
             )
  end

  test "POST /api/v1/external_objects", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ExternalObject{}} =
             ArchAstro.SDK.V1.ExternalObjects.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input.Nested.ObjectVariant1{
                     name: "test-name",
                     type: "r2_bucket"
                   },
                 service: "cloudflare"
               }
             )
  end

  test "POST /api/v1/external_objects returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ExternalObjects.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input.Nested.ObjectVariant1{
                     name: "test-name",
                     type: "r2_bucket"
                   },
                 service: "cloudflare"
               }
             )
  end

  test "POST /api/v1/external_objects returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.ExternalObjects.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input.Nested.ObjectVariant1{
                     name: "test-name",
                     type: "r2_bucket"
                   },
                 service: "cloudflare"
               }
             )
  end

  test "POST /api/v1/external_objects returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.ExternalObjects.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input.Nested.ObjectVariant1{
                     name: "test-name",
                     type: "r2_bucket"
                   },
                 service: "cloudflare"
               }
             )
  end

  test "POST /api/v1/external_objects returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.ExternalObjects.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input.Nested.ObjectVariant1{
                     name: "test-name",
                     type: "r2_bucket"
                   },
                 service: "cloudflare"
               }
             )
  end

  test "POST /api/v1/external_objects returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.ExternalObjects.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input.Nested.ObjectVariant1{
                     name: "test-name",
                     type: "r2_bucket"
                   },
                 service: "cloudflare"
               }
             )
  end

  test "POST /api/v1/external_objects returns 502" do
    client = ArchAstro.SDK.ContractSupport.error_client(502)

    assert {:error, %ArchAstro.SDK.Error{status: 502}} =
             ArchAstro.SDK.V1.ExternalObjects.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PostApiV1ExternalObjects.Input.Nested.ObjectVariant1{
                     name: "test-name",
                     type: "r2_bucket"
                   },
                 service: "cloudflare"
               }
             )
  end

  test "DELETE /api/v1/external_objects/{external_object}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.ExternalObjects.delete(client, "test-value")
  end

  test "DELETE /api/v1/external_objects/{external_object} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ExternalObjects.delete(client, "test-value")
  end

  test "DELETE /api/v1/external_objects/{external_object} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.ExternalObjects.delete(client, "test-value")
  end

  test "DELETE /api/v1/external_objects/{external_object} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.ExternalObjects.delete(client, "test-value")
  end

  test "DELETE /api/v1/external_objects/{external_object} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.ExternalObjects.delete(client, "test-value")
  end

  test "DELETE /api/v1/external_objects/{external_object} returns 502" do
    client = ArchAstro.SDK.ContractSupport.error_client(502)

    assert {:error, %ArchAstro.SDK.Error{status: 502}} =
             ArchAstro.SDK.V1.ExternalObjects.delete(client, "test-value")
  end

  test "GET /api/v1/external_objects/{external_object}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ExternalObject{}} =
             ArchAstro.SDK.V1.ExternalObjects.get(client, "test-value")
  end

  test "GET /api/v1/external_objects/{external_object} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ExternalObjects.get(client, "test-value")
  end

  test "GET /api/v1/external_objects/{external_object} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.ExternalObjects.get(client, "test-value")
  end

  test "PATCH /api/v1/external_objects/{external_object}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ExternalObject{}} =
             ArchAstro.SDK.V1.ExternalObjects.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input.Nested.ObjectVariant1{
                     storage_class: "test-value",
                     type: "r2_bucket"
                   }
               }
             )
  end

  test "PATCH /api/v1/external_objects/{external_object} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.ExternalObjects.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input.Nested.ObjectVariant1{
                     storage_class: "test-value",
                     type: "r2_bucket"
                   }
               }
             )
  end

  test "PATCH /api/v1/external_objects/{external_object} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.ExternalObjects.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input.Nested.ObjectVariant1{
                     storage_class: "test-value",
                     type: "r2_bucket"
                   }
               }
             )
  end

  test "PATCH /api/v1/external_objects/{external_object} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.ExternalObjects.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input.Nested.ObjectVariant1{
                     storage_class: "test-value",
                     type: "r2_bucket"
                   }
               }
             )
  end

  test "PATCH /api/v1/external_objects/{external_object} returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.ExternalObjects.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input.Nested.ObjectVariant1{
                     storage_class: "test-value",
                     type: "r2_bucket"
                   }
               }
             )
  end

  test "PATCH /api/v1/external_objects/{external_object} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.ExternalObjects.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input.Nested.ObjectVariant1{
                     storage_class: "test-value",
                     type: "r2_bucket"
                   }
               }
             )
  end

  test "PATCH /api/v1/external_objects/{external_object} returns 502" do
    client = ArchAstro.SDK.ContractSupport.error_client(502)

    assert {:error, %ArchAstro.SDK.Error{status: 502}} =
             ArchAstro.SDK.V1.ExternalObjects.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input{
                 object:
                   %ArchAstro.SDK.Types.Operations.PatchApiV1ExternalObjectsExternalObject.Input.Nested.ObjectVariant1{
                     storage_class: "test-value",
                     type: "r2_bucket"
                   }
               }
             )
  end
end
