# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e67d9f109410

defmodule ArchAstro.Contract.V1.FilesTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "POST /api/v1/files", %{client: client} do
    assert {:ok, %ArchAstro.Types.StorageFile{}} =
             ArchAstro.V1.Files.create(client, %ArchAstro.Types.Operations.PostApiV1Files.Input{
               content_type: "test-value",
               data: "test-value",
               filename: "test-value"
             })
  end

  test "POST /api/v1/files returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Files.create(client, %ArchAstro.Types.Operations.PostApiV1Files.Input{
               content_type: "test-value",
               data: "test-value",
               filename: "test-value"
             })
  end

  test "POST /api/v1/files returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Files.create(client, %ArchAstro.Types.Operations.PostApiV1Files.Input{
               content_type: "test-value",
               data: "test-value",
               filename: "test-value"
             })
  end

  test "POST /api/v1/files returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Files.create(client, %ArchAstro.Types.Operations.PostApiV1Files.Input{
               content_type: "test-value",
               data: "test-value",
               filename: "test-value"
             })
  end

  test "PATCH /api/v1/files/{file}", %{client: client} do
    assert {:ok, %ArchAstro.Types.StorageFile{}} =
             ArchAstro.V1.Files.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1FilesFile.Input{}
             )
  end

  test "PATCH /api/v1/files/{file} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Files.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1FilesFile.Input{}
             )
  end

  test "PATCH /api/v1/files/{file} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Files.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1FilesFile.Input{}
             )
  end

  test "PATCH /api/v1/files/{file} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Files.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1FilesFile.Input{}
             )
  end

  test "PATCH /api/v1/files/{file} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Files.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1FilesFile.Input{}
             )
  end

  test "GET /api/v1/files/{file}/avatar", %{client: client} do
    assert {:ok, %Req.Response{}} =
             ArchAstro.V1.Files.avatar(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1FilesFileAvatar.Params{token: "test-token"}
             )
  end

  test "GET /api/v1/files/{file}/avatar returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Files.avatar(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1FilesFileAvatar.Params{token: "test-token"}
             )
  end

  test "GET /api/v1/files/{file}/org_logo", %{client: client} do
    assert {:ok, %Req.Response{}} =
             ArchAstro.V1.Files.org_logo(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1FilesFileOrgLogo.Params{token: "test-token"}
             )
  end

  test "GET /api/v1/files/{file}/org_logo returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Files.org_logo(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1FilesFileOrgLogo.Params{token: "test-token"}
             )
  end

  test "GET /api/v1/files/{file}/share", %{client: client} do
    assert {:ok, %Req.Response{}} =
             ArchAstro.V1.Files.share(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1FilesFileShare.Params{token: "test-token"}
             )
  end

  test "GET /api/v1/files/{file}/share returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Files.share(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1FilesFileShare.Params{token: "test-token"}
             )
  end
end
