# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: e7e21ddb3597

defmodule ArchAstro.SDK.Contract.V1.InvitesTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "POST /api/v1/invites/accept", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.UserInvite{}} =
             ArchAstro.SDK.V1.Invites.accept(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1InvitesAccept.Input{key: "test-key"}
             )
  end

  test "POST /api/v1/invites/accept returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Invites.accept(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1InvitesAccept.Input{key: "test-key"}
             )
  end

  test "POST /api/v1/invites/accept returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Invites.accept(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1InvitesAccept.Input{key: "test-key"}
             )
  end

  test "POST /api/v1/invites/accept returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Invites.accept(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1InvitesAccept.Input{key: "test-key"}
             )
  end

  test "POST /api/v1/invites/accept returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.Invites.accept(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1InvitesAccept.Input{key: "test-key"}
             )
  end

  test "POST /api/v1/invites/accept returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Invites.accept(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1InvitesAccept.Input{key: "test-key"}
             )
  end

  test "POST /api/v1/invites/accept returns 429" do
    client = ArchAstro.SDK.ContractSupport.error_client(429)

    assert {:error, %ArchAstro.SDK.Error{status: 429}} =
             ArchAstro.SDK.V1.Invites.accept(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1InvitesAccept.Input{key: "test-key"}
             )
  end
end
