# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: b557c7f16226

defmodule ArchAstro.Contract.V1.KnowledgeSourcesTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/knowledge_sources", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1KnowledgeSources.Response{}} =
             ArchAstro.V1.KnowledgeSources.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1KnowledgeSources.Params{}
             )
  end

  test "GET /api/v1/knowledge_sources returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.KnowledgeSources.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1KnowledgeSources.Params{}
             )
  end

  test "GET /api/v1/knowledge_sources returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.KnowledgeSources.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1KnowledgeSources.Params{}
             )
  end

  test "POST /api/v1/knowledge_sources", %{client: client} do
    assert {:ok, %ArchAstro.Types.KnowledgeSource{}} =
             ArchAstro.V1.KnowledgeSources.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSources.Input{type: "test"}
             )
  end

  test "POST /api/v1/knowledge_sources returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.KnowledgeSources.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSources.Input{type: "test"}
             )
  end

  test "POST /api/v1/knowledge_sources returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.KnowledgeSources.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSources.Input{type: "test"}
             )
  end

  test "POST /api/v1/knowledge_sources returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.KnowledgeSources.create(
               client,
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSources.Input{type: "test"}
             )
  end

  test "DELETE /api/v1/knowledge_sources/{source}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.KnowledgeSources.delete(client, "test-value")
  end

  test "DELETE /api/v1/knowledge_sources/{source} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.KnowledgeSources.delete(client, "test-value")
  end

  test "DELETE /api/v1/knowledge_sources/{source} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.KnowledgeSources.delete(client, "test-value")
  end

  test "DELETE /api/v1/knowledge_sources/{source} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.KnowledgeSources.delete(client, "test-value")
  end

  test "GET /api/v1/knowledge_sources/{source}", %{client: client} do
    assert {:ok, %ArchAstro.Types.KnowledgeSource{}} =
             ArchAstro.V1.KnowledgeSources.get(client, "test-value")
  end

  test "GET /api/v1/knowledge_sources/{source} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.KnowledgeSources.get(client, "test-value")
  end

  test "GET /api/v1/knowledge_sources/{source} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.KnowledgeSources.get(client, "test-value")
  end

  test "GET /api/v1/knowledge_sources/{source} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.KnowledgeSources.get(client, "test-value")
  end

  test "PATCH /api/v1/knowledge_sources/{source}", %{client: client} do
    assert {:ok, %ArchAstro.Types.KnowledgeSource{}} =
             ArchAstro.V1.KnowledgeSources.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1KnowledgeSourcesSource.Input{}
             )
  end

  test "PATCH /api/v1/knowledge_sources/{source} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.KnowledgeSources.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1KnowledgeSourcesSource.Input{}
             )
  end

  test "PATCH /api/v1/knowledge_sources/{source} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.KnowledgeSources.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1KnowledgeSourcesSource.Input{}
             )
  end

  test "PATCH /api/v1/knowledge_sources/{source} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.KnowledgeSources.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1KnowledgeSourcesSource.Input{}
             )
  end

  test "PATCH /api/v1/knowledge_sources/{source} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.KnowledgeSources.update(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PatchApiV1KnowledgeSourcesSource.Input{}
             )
  end

  test "POST /api/v1/knowledge_sources/{source}/ingest", %{client: client} do
    assert {:ok, %ArchAstro.Types.ContextIngestion{}} =
             ArchAstro.V1.KnowledgeSources.ingest(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSourcesSourceIngest.Input{}
             )
  end

  test "POST /api/v1/knowledge_sources/{source}/ingest returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.KnowledgeSources.ingest(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSourcesSourceIngest.Input{}
             )
  end

  test "POST /api/v1/knowledge_sources/{source}/ingest returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.KnowledgeSources.ingest(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSourcesSourceIngest.Input{}
             )
  end

  test "POST /api/v1/knowledge_sources/{source}/ingest returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.KnowledgeSources.ingest(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSourcesSourceIngest.Input{}
             )
  end

  test "POST /api/v1/knowledge_sources/{source}/ingest returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.KnowledgeSources.ingest(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSourcesSourceIngest.Input{}
             )
  end

  test "POST /api/v1/knowledge_sources/{source}/ingest returns 429" do
    client = ArchAstro.ContractSupport.error_client(429)

    assert {:error, %ArchAstro.Error{status: 429}} =
             ArchAstro.V1.KnowledgeSources.ingest(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1KnowledgeSourcesSourceIngest.Input{}
             )
  end

  test "GET /api/v1/knowledge_sources/kinds", %{client: client} do
    assert {:ok, %ArchAstro.Types.KnowledgeSourceKindListResponse{}} =
             ArchAstro.V1.KnowledgeSources.Kinds.list(client)
  end

  test "GET /api/v1/knowledge_sources/kinds returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.KnowledgeSources.Kinds.list(client)
  end

  test "GET /api/v1/knowledge_sources/kinds returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.KnowledgeSources.Kinds.list(client)
  end
end
