# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 3f512721e46b

defmodule ArchAstro.Contract.V1.KvTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/kv", %{client: client} do
    assert {:ok, %ArchAstro.Types.KeyValueStorageEntryPage{}} =
             ArchAstro.V1.Kv.list(client, %ArchAstro.Types.Operations.GetApiV1Kv.Params{})
  end

  test "GET /api/v1/kv returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Kv.list(client, %ArchAstro.Types.Operations.GetApiV1Kv.Params{})
  end

  test "GET /api/v1/kv returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Kv.list(client, %ArchAstro.Types.Operations.GetApiV1Kv.Params{})
  end

  test "GET /api/v1/kv returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Kv.list(client, %ArchAstro.Types.Operations.GetApiV1Kv.Params{})
  end

  test "POST /api/v1/kv", %{client: client} do
    assert {:ok, %ArchAstro.Types.KeyValueStorageEntry{}} =
             ArchAstro.V1.Kv.create(client, %ArchAstro.Types.Operations.PostApiV1Kv.Input{
               key: "test-key",
               value: "test-value"
             })
  end

  test "POST /api/v1/kv returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Kv.create(client, %ArchAstro.Types.Operations.PostApiV1Kv.Input{
               key: "test-key",
               value: "test-value"
             })
  end

  test "POST /api/v1/kv returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Kv.create(client, %ArchAstro.Types.Operations.PostApiV1Kv.Input{
               key: "test-key",
               value: "test-value"
             })
  end

  test "POST /api/v1/kv returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Kv.create(client, %ArchAstro.Types.Operations.PostApiV1Kv.Input{
               key: "test-key",
               value: "test-value"
             })
  end

  test "POST /api/v1/kv returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Kv.create(client, %ArchAstro.Types.Operations.PostApiV1Kv.Input{
               key: "test-key",
               value: "test-value"
             })
  end

  test "POST /api/v1/kv returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Kv.create(client, %ArchAstro.Types.Operations.PostApiV1Kv.Input{
               key: "test-key",
               value: "test-value"
             })
  end

  test "DELETE /api/v1/kv/{key}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Kv.delete(client, "test-key")
  end

  test "DELETE /api/v1/kv/{key} returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)
    assert {:error, %ArchAstro.Error{status: 400}} = ArchAstro.V1.Kv.delete(client, "test-key")
  end

  test "DELETE /api/v1/kv/{key} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.Kv.delete(client, "test-key")
  end

  test "DELETE /api/v1/kv/{key} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)
    assert {:error, %ArchAstro.Error{status: 403}} = ArchAstro.V1.Kv.delete(client, "test-key")
  end

  test "DELETE /api/v1/kv/{key} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)
    assert {:error, %ArchAstro.Error{status: 404}} = ArchAstro.V1.Kv.delete(client, "test-key")
  end

  test "GET /api/v1/kv/{key}", %{client: client} do
    assert {:ok, %ArchAstro.Types.KeyValueStorageEntry{}} =
             ArchAstro.V1.Kv.get(
               client,
               "test-key",
               %ArchAstro.Types.Operations.GetApiV1KvKey.Params{}
             )
  end

  test "GET /api/v1/kv/{key} returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Kv.get(
               client,
               "test-key",
               %ArchAstro.Types.Operations.GetApiV1KvKey.Params{}
             )
  end

  test "GET /api/v1/kv/{key} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Kv.get(
               client,
               "test-key",
               %ArchAstro.Types.Operations.GetApiV1KvKey.Params{}
             )
  end

  test "GET /api/v1/kv/{key} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Kv.get(
               client,
               "test-key",
               %ArchAstro.Types.Operations.GetApiV1KvKey.Params{}
             )
  end

  test "GET /api/v1/kv/{key} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Kv.get(
               client,
               "test-key",
               %ArchAstro.Types.Operations.GetApiV1KvKey.Params{}
             )
  end

  test "PUT /api/v1/kv/{key}", %{client: client} do
    assert {:ok, %ArchAstro.Types.KeyValueStorageEntry{}} =
             ArchAstro.V1.Kv.upsert(
               client,
               "test-key",
               %ArchAstro.Types.Operations.PutApiV1KvKey.Input{value: "test-value"}
             )
  end

  test "PUT /api/v1/kv/{key} returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Kv.upsert(
               client,
               "test-key",
               %ArchAstro.Types.Operations.PutApiV1KvKey.Input{value: "test-value"}
             )
  end

  test "PUT /api/v1/kv/{key} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Kv.upsert(
               client,
               "test-key",
               %ArchAstro.Types.Operations.PutApiV1KvKey.Input{value: "test-value"}
             )
  end

  test "PUT /api/v1/kv/{key} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Kv.upsert(
               client,
               "test-key",
               %ArchAstro.Types.Operations.PutApiV1KvKey.Input{value: "test-value"}
             )
  end

  test "PUT /api/v1/kv/{key} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Kv.upsert(
               client,
               "test-key",
               %ArchAstro.Types.Operations.PutApiV1KvKey.Input{value: "test-value"}
             )
  end

  test "PUT /api/v1/kv/{key} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Kv.upsert(
               client,
               "test-key",
               %ArchAstro.Types.Operations.PutApiV1KvKey.Input{value: "test-value"}
             )
  end
end
