# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: de70acf55667

defmodule ArchAstro.Contract.V1.NotificationsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/notifications", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1Notifications.Response{}} =
             ArchAstro.V1.Notifications.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1Notifications.Params{}
             )
  end

  test "GET /api/v1/notifications returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Notifications.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1Notifications.Params{}
             )
  end

  test "GET /api/v1/notifications returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Notifications.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1Notifications.Params{}
             )
  end

  test "GET /api/v1/notifications returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Notifications.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1Notifications.Params{}
             )
  end

  test "POST /api/v1/notifications/read_all", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Notifications.read_all(client)
  end

  test "POST /api/v1/notifications/read_all returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.Notifications.read_all(client)
  end

  test "POST /api/v1/notifications/read_all returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)
    assert {:error, %ArchAstro.Error{status: 403}} = ArchAstro.V1.Notifications.read_all(client)
  end

  test "POST /api/v1/notifications/send", %{client: client} do
    assert {:ok, %ArchAstro.Types.Notification{}} =
             ArchAstro.V1.Notifications.send(
               client,
               %ArchAstro.Types.Operations.PostApiV1NotificationsSend.Input{
                 type: "test",
                 user: "test-value"
               }
             )
  end

  test "POST /api/v1/notifications/send returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Notifications.send(
               client,
               %ArchAstro.Types.Operations.PostApiV1NotificationsSend.Input{
                 type: "test",
                 user: "test-value"
               }
             )
  end

  test "POST /api/v1/notifications/send returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Notifications.send(
               client,
               %ArchAstro.Types.Operations.PostApiV1NotificationsSend.Input{
                 type: "test",
                 user: "test-value"
               }
             )
  end

  test "POST /api/v1/notifications/send returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Notifications.send(
               client,
               %ArchAstro.Types.Operations.PostApiV1NotificationsSend.Input{
                 type: "test",
                 user: "test-value"
               }
             )
  end

  test "POST /api/v1/notifications/send returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Notifications.send(
               client,
               %ArchAstro.Types.Operations.PostApiV1NotificationsSend.Input{
                 type: "test",
                 user: "test-value"
               }
             )
  end

  test "POST /api/v1/notifications/send returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Notifications.send(
               client,
               %ArchAstro.Types.Operations.PostApiV1NotificationsSend.Input{
                 type: "test",
                 user: "test-value"
               }
             )
  end

  test "GET /api/v1/notifications/unread_count", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1NotificationsUnreadCount.Response{}} =
             ArchAstro.V1.Notifications.unread_count(client)
  end

  test "GET /api/v1/notifications/unread_count returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.Notifications.unread_count(client)
  end

  test "GET /api/v1/notifications/unread_count returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)
    assert {:error, %ArchAstro.Error{status: 403}} = ArchAstro.V1.Notifications.unread_count(client)
  end

  test "POST /api/v1/notifications/{notification}/archive", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Notifications.archive(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/archive returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Notifications.archive(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/archive returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Notifications.archive(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/archive returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Notifications.archive(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/read", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Notifications.read(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/read returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Notifications.read(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/read returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Notifications.read(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/read returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Notifications.read(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/unarchive", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Notifications.unarchive(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/unarchive returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Notifications.unarchive(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/unarchive returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Notifications.unarchive(client, "test-value")
  end

  test "POST /api/v1/notifications/{notification}/unarchive returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Notifications.unarchive(client, "test-value")
  end
end
