# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 6f453719f9e8

defmodule ArchAstro.Contract.V1.OauthTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /oauth/scopes", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetOauthScopes.Response{}} =
             ArchAstro.V1.Oauth.scopes(client)
  end

  test "POST /oauth/token", %{client: client} do
    assert {:ok, %ArchAstro.Types.OAuthTokenResponse{}} =
             ArchAstro.V1.Oauth.token(client, %ArchAstro.Types.Operations.PostOauthToken.Input{
               grant_type: "test-value"
             })
  end

  test "POST /oauth/token returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Oauth.token(client, %ArchAstro.Types.Operations.PostOauthToken.Input{
               grant_type: "test-value"
             })
  end

  test "POST /oauth/token returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Oauth.token(client, %ArchAstro.Types.Operations.PostOauthToken.Input{
               grant_type: "test-value"
             })
  end

  test "POST /oauth/token returns 429" do
    client = ArchAstro.ContractSupport.error_client(429)

    assert {:error, %ArchAstro.Error{status: 429}} =
             ArchAstro.V1.Oauth.token(client, %ArchAstro.Types.Operations.PostOauthToken.Input{
               grant_type: "test-value"
             })
  end

  test "POST /oauth/device/approve", %{client: client} do
    assert {:ok, %ArchAstro.Types.DeviceAuthorizationStatusResponse{}} =
             ArchAstro.V1.Oauth.Device.approve(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceApprove.Input{user_code: "test-value"}
             )
  end

  test "POST /oauth/device/approve returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Oauth.Device.approve(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceApprove.Input{user_code: "test-value"}
             )
  end

  test "POST /oauth/device/approve returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Oauth.Device.approve(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceApprove.Input{user_code: "test-value"}
             )
  end

  test "POST /oauth/device/authorize", %{client: client} do
    assert {:ok, %ArchAstro.Types.DeviceAuthorizationResponse{}} =
             ArchAstro.V1.Oauth.Device.authorize(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceAuthorize.Input{client: "test-value"}
             )
  end

  test "POST /oauth/device/authorize returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Oauth.Device.authorize(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceAuthorize.Input{client: "test-value"}
             )
  end

  test "POST /oauth/device/authorize returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Oauth.Device.authorize(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceAuthorize.Input{client: "test-value"}
             )
  end

  test "POST /oauth/device/authorize returns 429" do
    client = ArchAstro.ContractSupport.error_client(429)

    assert {:error, %ArchAstro.Error{status: 429}} =
             ArchAstro.V1.Oauth.Device.authorize(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceAuthorize.Input{client: "test-value"}
             )
  end

  test "POST /oauth/device/deny", %{client: client} do
    assert {:ok, %ArchAstro.Types.DeviceAuthorizationStatusResponse{}} =
             ArchAstro.V1.Oauth.Device.deny(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceDeny.Input{user_code: "test-value"}
             )
  end

  test "POST /oauth/device/deny returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Oauth.Device.deny(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceDeny.Input{user_code: "test-value"}
             )
  end

  test "POST /oauth/device/deny returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Oauth.Device.deny(
               client,
               %ArchAstro.Types.Operations.PostOauthDeviceDeny.Input{user_code: "test-value"}
             )
  end
end
