# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: f72dc77dc476

defmodule ArchAstro.Contract.V1.PrivateServiceDefinitionsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/private_service_definitions/{app_id}/{private_service_id}", %{client: client} do
    assert {:ok, value} = ArchAstro.V1.PrivateServiceDefinitions.get(client, "test-id", "test-id")
    assert is_binary(value)
  end

  test "GET /api/v1/private_service_definitions/{app_id}/{private_service_id} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.PrivateServiceDefinitions.get(client, "test-id", "test-id")
  end

  test "GET /api/v1/private_service_definitions/{app_id}/{private_service_id} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.PrivateServiceDefinitions.get(client, "test-id", "test-id")
  end

  test "GET /api/v1/private_service_definitions/{app_id}/{private_service_id} returns 503" do
    client = ArchAstro.ContractSupport.error_client(503)

    assert {:error, %ArchAstro.Error{status: 503}} =
             ArchAstro.V1.PrivateServiceDefinitions.get(client, "test-id", "test-id")
  end
end
