# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 90c9a5599f9e

defmodule ArchAstro.SDK.Contract.V1.PrivateServicesTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/private_services", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.PrivateServicePage{}} =
             ArchAstro.SDK.V1.PrivateServices.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServices.Params{}
             )
  end

  test "GET /api/v1/private_services returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.PrivateServices.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServices.Params{}
             )
  end

  test "GET /api/v1/private_services returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.PrivateServices.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServices.Params{}
             )
  end

  test "GET /api/v1/private_services returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.PrivateServices.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServices.Params{}
             )
  end

  test "GET /api/v1/private_services returns 503" do
    client = ArchAstro.SDK.ContractSupport.error_client(503)

    assert {:error, %ArchAstro.SDK.Error{status: 503}} =
             ArchAstro.SDK.V1.PrivateServices.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServices.Params{}
             )
  end

  test "POST /api/v1/private_services", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.PrivateService{}} =
             ArchAstro.SDK.V1.PrivateServices.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1PrivateServices.Input{functions: []}
             )
  end

  test "POST /api/v1/private_services returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.PrivateServices.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1PrivateServices.Input{functions: []}
             )
  end

  test "POST /api/v1/private_services returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.PrivateServices.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1PrivateServices.Input{functions: []}
             )
  end

  test "POST /api/v1/private_services returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.PrivateServices.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1PrivateServices.Input{functions: []}
             )
  end

  test "POST /api/v1/private_services returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.PrivateServices.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1PrivateServices.Input{functions: []}
             )
  end

  test "POST /api/v1/private_services returns 503" do
    client = ArchAstro.SDK.ContractSupport.error_client(503)

    assert {:error, %ArchAstro.SDK.Error{status: 503}} =
             ArchAstro.SDK.V1.PrivateServices.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1PrivateServices.Input{functions: []}
             )
  end

  test "GET /api/v1/private_services/{private_service_id}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.PrivateService{}} =
             ArchAstro.SDK.V1.PrivateServices.get(
               client,
               "test-id",
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServicesPrivateServiceId.Params{}
             )
  end

  test "GET /api/v1/private_services/{private_service_id} returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.PrivateServices.get(
               client,
               "test-id",
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServicesPrivateServiceId.Params{}
             )
  end

  test "GET /api/v1/private_services/{private_service_id} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.PrivateServices.get(
               client,
               "test-id",
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServicesPrivateServiceId.Params{}
             )
  end

  test "GET /api/v1/private_services/{private_service_id} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.PrivateServices.get(
               client,
               "test-id",
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServicesPrivateServiceId.Params{}
             )
  end

  test "GET /api/v1/private_services/{private_service_id} returns 503" do
    client = ArchAstro.SDK.ContractSupport.error_client(503)

    assert {:error, %ArchAstro.SDK.Error{status: 503}} =
             ArchAstro.SDK.V1.PrivateServices.get(
               client,
               "test-id",
               %ArchAstro.SDK.Types.Operations.GetApiV1PrivateServicesPrivateServiceId.Params{}
             )
  end
end
