# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 7c2c59673de5

defmodule ArchAstro.SDK.Contract.V1.RelaysTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "POST /api/v1/relays", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Relay{}} =
             ArchAstro.SDK.V1.Relays.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Relays.Input{
                 purpose: "test-value",
                 ttl_seconds: 1
               }
             )
  end

  test "POST /api/v1/relays returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Relays.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Relays.Input{
                 purpose: "test-value",
                 ttl_seconds: 1
               }
             )
  end

  test "POST /api/v1/relays returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Relays.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Relays.Input{
                 purpose: "test-value",
                 ttl_seconds: 1
               }
             )
  end

  test "POST /api/v1/relays returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Relays.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Relays.Input{
                 purpose: "test-value",
                 ttl_seconds: 1
               }
             )
  end

  test "DELETE /api/v1/relays/{relay}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Relay{}} =
             ArchAstro.SDK.V1.Relays.delete(client, "test-value")
  end

  test "DELETE /api/v1/relays/{relay} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Relays.delete(client, "test-value")
  end

  test "DELETE /api/v1/relays/{relay} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Relays.delete(client, "test-value")
  end

  test "DELETE /api/v1/relays/{relay} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Relays.delete(client, "test-value")
  end

  test "GET /api/v1/relays/{relay}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Relay{}} = ArchAstro.SDK.V1.Relays.get(client, "test-value")
  end

  test "GET /api/v1/relays/{relay} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Relays.get(client, "test-value")
  end

  test "GET /api/v1/relays/{relay} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Relays.get(client, "test-value")
  end

  test "GET /api/v1/relays/{relay} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Relays.get(client, "test-value")
  end

  test "POST /api/v1/relays/{relay}/extend", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Relay{}} =
             ArchAstro.SDK.V1.Relays.extend(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1RelaysRelayExtend.Input{ttl_seconds: 1}
             )
  end

  test "POST /api/v1/relays/{relay}/extend returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Relays.extend(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1RelaysRelayExtend.Input{ttl_seconds: 1}
             )
  end

  test "POST /api/v1/relays/{relay}/extend returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Relays.extend(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1RelaysRelayExtend.Input{ttl_seconds: 1}
             )
  end

  test "POST /api/v1/relays/{relay}/extend returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Relays.extend(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1RelaysRelayExtend.Input{ttl_seconds: 1}
             )
  end
end
