# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: d624a1add758

defmodule ArchAstro.SDK.Contract.V1.ScriptsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/scripts/language", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ScriptLanguageSpec{}} =
             ArchAstro.SDK.V1.Scripts.language(client)
  end

  test "GET /api/v1/scripts/language returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.SDK.Error{status: 401}} = ArchAstro.SDK.V1.Scripts.language(client)
  end

  test "GET /api/v1/scripts/llm.txt", %{client: client} do
    assert {:ok, %Req.Response{}} = ArchAstro.SDK.V1.Scripts.llm_txt(client)
  end

  test "GET /api/v1/scripts/llm.txt returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.SDK.Error{status: 401}} = ArchAstro.SDK.V1.Scripts.llm_txt(client)
  end

  test "POST /api/v1/scripts/run", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ScriptRunResult{}} =
             ArchAstro.SDK.V1.Scripts.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsRun.Input{}
             )
  end

  test "POST /api/v1/scripts/run returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Scripts.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsRun.Input{}
             )
  end

  test "POST /api/v1/scripts/run returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Scripts.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsRun.Input{}
             )
  end

  test "POST /api/v1/scripts/run returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Scripts.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsRun.Input{}
             )
  end

  test "POST /api/v1/scripts/run returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Scripts.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsRun.Input{}
             )
  end

  test "GET /api/v1/scripts/runtime_env_vars", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.RuntimeEnvVarList{}} =
             ArchAstro.SDK.V1.Scripts.runtime_env_vars(client)
  end

  test "GET /api/v1/scripts/runtime_env_vars returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Scripts.runtime_env_vars(client)
  end

  test "GET /api/v1/scripts/runtime_env_vars returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Scripts.runtime_env_vars(client)
  end

  test "POST /api/v1/scripts/test", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ScriptTestRunResult{}} =
             ArchAstro.SDK.V1.Scripts.test(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsTest.Input{}
             )
  end

  test "POST /api/v1/scripts/test returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Scripts.test(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsTest.Input{}
             )
  end

  test "POST /api/v1/scripts/test returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Scripts.test(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsTest.Input{}
             )
  end

  test "POST /api/v1/scripts/validate", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ExpressionValidation{}} =
             ArchAstro.SDK.V1.Scripts.validate(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsValidate.Input{}
             )
  end

  test "POST /api/v1/scripts/validate returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Scripts.validate(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1ScriptsValidate.Input{}
             )
  end
end
