# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: ee54a5af9ce1

defmodule ArchAstro.SDK.Contract.V1.SlackChannelBindingsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/slack_channel_bindings", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.SlackChannelBindingListResponse{}} =
             ArchAstro.SDK.V1.SlackChannelBindings.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindings.Params{}
             )
  end

  test "GET /api/v1/slack_channel_bindings returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.SlackChannelBindings.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindings.Params{}
             )
  end

  test "GET /api/v1/slack_channel_bindings returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SlackChannelBindings.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindings.Params{}
             )
  end

  test "GET /api/v1/slack_channel_bindings returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SlackChannelBindings.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindings.Params{}
             )
  end

  test "POST /api/v1/slack_channel_bindings", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.SlackChannelBinding{}} =
             ArchAstro.SDK.V1.SlackChannelBindings.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindings.Input{
                 agent_user_ids: [],
                 channel_id: "test-id",
                 slack_team_id: "test-id",
                 team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.SlackChannelBindings.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindings.Input{
                 agent_user_ids: [],
                 channel_id: "test-id",
                 slack_team_id: "test-id",
                 team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SlackChannelBindings.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindings.Input{
                 agent_user_ids: [],
                 channel_id: "test-id",
                 slack_team_id: "test-id",
                 team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SlackChannelBindings.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindings.Input{
                 agent_user_ids: [],
                 channel_id: "test-id",
                 slack_team_id: "test-id",
                 team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.SlackChannelBindings.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindings.Input{
                 agent_user_ids: [],
                 channel_id: "test-id",
                 slack_team_id: "test-id",
                 team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.SlackChannelBindings.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindings.Input{
                 agent_user_ids: [],
                 channel_id: "test-id",
                 slack_team_id: "test-id",
                 team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.SlackChannelBindings.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindings.Input{
                 agent_user_ids: [],
                 channel_id: "test-id",
                 slack_team_id: "test-id",
                 team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.SlackChannelBinding{}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision returns 500" do
    client = ArchAstro.SDK.ContractSupport.error_client(500)

    assert {:error, %ArchAstro.SDK.Error{status: 500}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/provision returns 502" do
    client = ArchAstro.SDK.ContractSupport.error_client(502)

    assert {:error, %ArchAstro.SDK.Error{status: 502}} =
             ArchAstro.SDK.V1.SlackChannelBindings.provision(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsProvision.Input{
                 customer_key: "test-key",
                 customer_label: "test-value",
                 slack_team_id: "test-id",
                 template_config_id: "test-id"
               }
             )
  end

  test "DELETE /api/v1/slack_channel_bindings/{channel}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.DeleteApiV1SlackChannelBindingsChannel.Response{}} =
             ArchAstro.SDK.V1.SlackChannelBindings.delete(client, "test-value")
  end

  test "DELETE /api/v1/slack_channel_bindings/{channel} returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.SlackChannelBindings.delete(client, "test-value")
  end

  test "DELETE /api/v1/slack_channel_bindings/{channel} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SlackChannelBindings.delete(client, "test-value")
  end

  test "DELETE /api/v1/slack_channel_bindings/{channel} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SlackChannelBindings.delete(client, "test-value")
  end

  test "DELETE /api/v1/slack_channel_bindings/{channel} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.SlackChannelBindings.delete(client, "test-value")
  end

  test "DELETE /api/v1/slack_channel_bindings/{channel} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.SlackChannelBindings.delete(client, "test-value")
  end

  test "GET /api/v1/slack_channel_bindings/{channel}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.SlackChannelBinding{}} =
             ArchAstro.SDK.V1.SlackChannelBindings.get(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindingsChannel.Params{
                 slack_team_id: "test-id"
               }
             )
  end

  test "GET /api/v1/slack_channel_bindings/{channel} returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.SlackChannelBindings.get(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindingsChannel.Params{
                 slack_team_id: "test-id"
               }
             )
  end

  test "GET /api/v1/slack_channel_bindings/{channel} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SlackChannelBindings.get(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindingsChannel.Params{
                 slack_team_id: "test-id"
               }
             )
  end

  test "GET /api/v1/slack_channel_bindings/{channel} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SlackChannelBindings.get(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindingsChannel.Params{
                 slack_team_id: "test-id"
               }
             )
  end

  test "GET /api/v1/slack_channel_bindings/{channel} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.SlackChannelBindings.get(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindingsChannel.Params{
                 slack_team_id: "test-id"
               }
             )
  end

  test "GET /api/v1/slack_channel_bindings/{channel} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.SlackChannelBindings.get(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1SlackChannelBindingsChannel.Params{
                 slack_team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/{channel}/deposit_thread", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.SlackChannelBinding{}} =
             ArchAstro.SDK.V1.SlackChannelBindings.deposit_thread(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsChannelDepositThread.Input{
                 slack_team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/{channel}/deposit_thread returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.SlackChannelBindings.deposit_thread(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsChannelDepositThread.Input{
                 slack_team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/{channel}/deposit_thread returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SlackChannelBindings.deposit_thread(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsChannelDepositThread.Input{
                 slack_team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/{channel}/deposit_thread returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SlackChannelBindings.deposit_thread(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsChannelDepositThread.Input{
                 slack_team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/{channel}/deposit_thread returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.SlackChannelBindings.deposit_thread(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsChannelDepositThread.Input{
                 slack_team_id: "test-id"
               }
             )
  end

  test "POST /api/v1/slack_channel_bindings/{channel}/deposit_thread returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.SlackChannelBindings.deposit_thread(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1SlackChannelBindingsChannelDepositThread.Input{
                 slack_team_id: "test-id"
               }
             )
  end
end
