# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: b930f02daa78

defmodule ArchAstro.SDK.Contract.V1.SolutionInstancesTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/solution_instances", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.SolutionInstanceListResponse{}} =
             ArchAstro.SDK.V1.SolutionInstances.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SolutionInstances.Params{
                 solution_template_config_id: "test-id"
               }
             )
  end

  test "GET /api/v1/solution_instances returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.SolutionInstances.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SolutionInstances.Params{
                 solution_template_config_id: "test-id"
               }
             )
  end

  test "GET /api/v1/solution_instances returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SolutionInstances.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SolutionInstances.Params{
                 solution_template_config_id: "test-id"
               }
             )
  end

  test "GET /api/v1/solution_instances returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SolutionInstances.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SolutionInstances.Params{
                 solution_template_config_id: "test-id"
               }
             )
  end
end
