# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 0407a0fa1699

defmodule ArchAstro.SDK.Contract.V1.SolutionCategoriesTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/solution_categories", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.SolutionCategoryListResponse{}} =
             ArchAstro.SDK.V1.SolutionCategories.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SolutionCategories.Params{}
             )
  end

  test "GET /api/v1/solution_categories returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SolutionCategories.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SolutionCategories.Params{}
             )
  end

  test "GET /api/v1/solution_categories returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SolutionCategories.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1SolutionCategories.Params{}
             )
  end
end
