# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 21fe8058c516

defmodule ArchAstro.Contract.V1.SolutionTagsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/solution_tags", %{client: client} do
    assert {:ok, %ArchAstro.Types.SolutionTagListResponse{}} =
             ArchAstro.V1.SolutionTags.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1SolutionTags.Params{}
             )
  end

  test "GET /api/v1/solution_tags returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.SolutionTags.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1SolutionTags.Params{}
             )
  end

  test "GET /api/v1/solution_tags returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.SolutionTags.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1SolutionTags.Params{}
             )
  end
end
