# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: b5844c634cd3

defmodule ArchAstro.SDK.Contract.V1.SshKeysTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "DELETE /api/v1/ssh_keys/{ssh_key}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.SshKeys.delete(client, "test-key")
  end

  test "DELETE /api/v1/ssh_keys/{ssh_key} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.SshKeys.delete(client, "test-key")
  end

  test "DELETE /api/v1/ssh_keys/{ssh_key} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.SshKeys.delete(client, "test-key")
  end

  test "DELETE /api/v1/ssh_keys/{ssh_key} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.SshKeys.delete(client, "test-key")
  end
end
