# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 896c04df16d0

defmodule ArchAstro.Contract.V1.StatusTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/status/ping", %{client: client} do
    assert {:ok, %ArchAstro.Types.StatusPing{}} = ArchAstro.V1.Status.ping(client)
  end
end
