# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 375366523120

defmodule ArchAstro.Contract.V1.TasksTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "DELETE /api/v1/tasks/{task}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Tasks.delete(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.Tasks.delete(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)
    assert {:error, %ArchAstro.Error{status: 404}} = ArchAstro.V1.Tasks.delete(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)
    assert {:error, %ArchAstro.Error{status: 422}} = ArchAstro.V1.Tasks.delete(client, "test-value")
  end

  test "GET /api/v1/tasks/{task}", %{client: client} do
    assert {:ok, %ArchAstro.Types.Task{}} =
             ArchAstro.V1.Tasks.get(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTask.Params{}
             )
  end

  test "GET /api/v1/tasks/{task} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.get(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTask.Params{}
             )
  end

  test "GET /api/v1/tasks/{task} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.get(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTask.Params{}
             )
  end

  test "GET /api/v1/tasks/{task} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.get(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTask.Params{}
             )
  end

  test "PUT /api/v1/tasks/{task}", %{client: client} do
    assert {:ok, %ArchAstro.Types.Task{}} =
             ArchAstro.V1.Tasks.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTask.Input{}
             )
  end

  test "PUT /api/v1/tasks/{task} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTask.Input{}
             )
  end

  test "PUT /api/v1/tasks/{task} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Tasks.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTask.Input{}
             )
  end

  test "PUT /api/v1/tasks/{task} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTask.Input{}
             )
  end

  test "PUT /api/v1/tasks/{task} returns 409" do
    client = ArchAstro.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.Error{status: 409}} =
             ArchAstro.V1.Tasks.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTask.Input{}
             )
  end

  test "PUT /api/v1/tasks/{task} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTask.Input{}
             )
  end

  test "GET /api/v1/tasks/{task}/activity", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1TasksTaskActivity.Response{}} =
             ArchAstro.V1.Tasks.activity(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskActivity.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/activity returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.activity(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskActivity.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/activity returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.activity(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskActivity.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/activity returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.activity(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskActivity.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blocking", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1TasksTaskBlocking.Response{}} =
             ArchAstro.V1.Tasks.blocking(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlocking.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blocking returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.blocking(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlocking.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blocking returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.blocking(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlocking.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blocking returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.blocking(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlocking.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/subtasks", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1TasksTaskSubtasks.Response{}} =
             ArchAstro.V1.Tasks.subtasks(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskSubtasks.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/subtasks returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.subtasks(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskSubtasks.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/subtasks returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.subtasks(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskSubtasks.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/subtasks returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.subtasks(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskSubtasks.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blockers", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1TasksTaskBlockers.Response{}} =
             ArchAstro.V1.Tasks.Blockers.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlockers.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blockers returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Blockers.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlockers.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blockers returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Blockers.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlockers.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/blockers returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Blockers.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskBlockers.Params{}
             )
  end

  test "POST /api/v1/tasks/{task}/blockers", %{client: client} do
    assert {:ok, %ArchAstro.Types.Task{}} =
             ArchAstro.V1.Tasks.Blockers.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskBlockers.Input{blocker: "test-value"}
             )
  end

  test "POST /api/v1/tasks/{task}/blockers returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Blockers.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskBlockers.Input{blocker: "test-value"}
             )
  end

  test "POST /api/v1/tasks/{task}/blockers returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Blockers.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskBlockers.Input{blocker: "test-value"}
             )
  end

  test "POST /api/v1/tasks/{task}/blockers returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Blockers.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskBlockers.Input{blocker: "test-value"}
             )
  end

  test "DELETE /api/v1/tasks/{task}/blockers/{blocker}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Tasks.Blockers.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/blockers/{blocker} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Blockers.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/blockers/{blocker} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Blockers.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/blockers/{blocker} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Blockers.delete(client, "test-value", "test-value")
  end

  test "GET /api/v1/tasks/{task}/comments", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1TasksTaskComments.Response{}} =
             ArchAstro.V1.Tasks.Comments.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskComments.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/comments returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Comments.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskComments.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/comments returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Comments.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskComments.Params{}
             )
  end

  test "GET /api/v1/tasks/{task}/comments returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Comments.list(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1TasksTaskComments.Params{}
             )
  end

  test "POST /api/v1/tasks/{task}/comments", %{client: client} do
    assert {:ok, %ArchAstro.Types.TaskComment{}} =
             ArchAstro.V1.Tasks.Comments.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input{
                 comment:
                   %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input.Nested.Comment{
                     body: "test-value"
                   }
               }
             )
  end

  test "POST /api/v1/tasks/{task}/comments returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Comments.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input{
                 comment:
                   %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input.Nested.Comment{
                     body: "test-value"
                   }
               }
             )
  end

  test "POST /api/v1/tasks/{task}/comments returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Comments.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input{
                 comment:
                   %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input.Nested.Comment{
                     body: "test-value"
                   }
               }
             )
  end

  test "POST /api/v1/tasks/{task}/comments returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Comments.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input{
                 comment:
                   %ArchAstro.Types.Operations.PostApiV1TasksTaskComments.Input.Nested.Comment{
                     body: "test-value"
                   }
               }
             )
  end

  test "DELETE /api/v1/tasks/{task}/comments/{comment}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Tasks.Comments.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/comments/{comment} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Comments.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/comments/{comment} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Tasks.Comments.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/comments/{comment} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Comments.delete(client, "test-value", "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/comments/{comment} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Comments.delete(client, "test-value", "test-value")
  end

  test "PUT /api/v1/tasks/{task}/comments/{comment}", %{client: client} do
    assert {:ok, %ArchAstro.Types.TaskComment{}} =
             ArchAstro.V1.Tasks.Comments.replace(
               client,
               "test-value",
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTaskCommentsComment.Input{
                 body: "test-value"
               }
             )
  end

  test "PUT /api/v1/tasks/{task}/comments/{comment} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Comments.replace(
               client,
               "test-value",
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTaskCommentsComment.Input{
                 body: "test-value"
               }
             )
  end

  test "PUT /api/v1/tasks/{task}/comments/{comment} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Tasks.Comments.replace(
               client,
               "test-value",
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTaskCommentsComment.Input{
                 body: "test-value"
               }
             )
  end

  test "PUT /api/v1/tasks/{task}/comments/{comment} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Comments.replace(
               client,
               "test-value",
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTaskCommentsComment.Input{
                 body: "test-value"
               }
             )
  end

  test "PUT /api/v1/tasks/{task}/comments/{comment} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Comments.replace(
               client,
               "test-value",
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1TasksTaskCommentsComment.Input{
                 body: "test-value"
               }
             )
  end

  test "DELETE /api/v1/tasks/{task}/lease", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Tasks.Lease.remove(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/lease returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Lease.remove(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/lease returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Tasks.Lease.remove(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/lease returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Lease.remove(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/lease returns 409" do
    client = ArchAstro.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.Error{status: 409}} =
             ArchAstro.V1.Tasks.Lease.remove(client, "test-value")
  end

  test "DELETE /api/v1/tasks/{task}/lease returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Lease.remove(client, "test-value")
  end

  test "GET /api/v1/tasks/{task}/lease", %{client: client} do
    assert {:ok, %ArchAstro.Types.TaskSessionLeaseSummary{}} =
             ArchAstro.V1.Tasks.Lease.list(client, "test-value")
  end

  test "GET /api/v1/tasks/{task}/lease returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Lease.list(client, "test-value")
  end

  test "GET /api/v1/tasks/{task}/lease returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Tasks.Lease.list(client, "test-value")
  end

  test "GET /api/v1/tasks/{task}/lease returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Lease.list(client, "test-value")
  end

  test "GET /api/v1/tasks/{task}/lease returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Lease.list(client, "test-value")
  end

  test "POST /api/v1/tasks/{task}/lease", %{client: client} do
    assert {:ok, %ArchAstro.Types.TaskSessionLease{}} =
             ArchAstro.V1.Tasks.Lease.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLease.Input{
                 harness: "test-value",
                 lease_id: "test-id",
                 session_id: "test-id",
                 session_name: "test-value"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Lease.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLease.Input{
                 harness: "test-value",
                 lease_id: "test-id",
                 session_id: "test-id",
                 session_name: "test-value"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Tasks.Lease.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLease.Input{
                 harness: "test-value",
                 lease_id: "test-id",
                 session_id: "test-id",
                 session_name: "test-value"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Lease.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLease.Input{
                 harness: "test-value",
                 lease_id: "test-id",
                 session_id: "test-id",
                 session_name: "test-value"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease returns 409" do
    client = ArchAstro.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.Error{status: 409}} =
             ArchAstro.V1.Tasks.Lease.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLease.Input{
                 harness: "test-value",
                 lease_id: "test-id",
                 session_id: "test-id",
                 session_name: "test-value"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Lease.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLease.Input{
                 harness: "test-value",
                 lease_id: "test-id",
                 session_id: "test-id",
                 session_name: "test-value"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease/renew", %{client: client} do
    assert {:ok, %ArchAstro.Types.TaskSessionLease{}} =
             ArchAstro.V1.Tasks.Lease.renew(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLeaseRenew.Input{
                 lease_id: "test-id",
                 session_id: "test-id"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease/renew returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Tasks.Lease.renew(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLeaseRenew.Input{
                 lease_id: "test-id",
                 session_id: "test-id"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease/renew returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Tasks.Lease.renew(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLeaseRenew.Input{
                 lease_id: "test-id",
                 session_id: "test-id"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease/renew returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Tasks.Lease.renew(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLeaseRenew.Input{
                 lease_id: "test-id",
                 session_id: "test-id"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease/renew returns 409" do
    client = ArchAstro.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.Error{status: 409}} =
             ArchAstro.V1.Tasks.Lease.renew(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLeaseRenew.Input{
                 lease_id: "test-id",
                 session_id: "test-id"
               }
             )
  end

  test "POST /api/v1/tasks/{task}/lease/renew returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Tasks.Lease.renew(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1TasksTaskLeaseRenew.Input{
                 lease_id: "test-id",
                 session_id: "test-id"
               }
             )
  end
end
