# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 90371490d10e

defmodule ArchAstro.Contract.V1.TeamMembershipsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "GET /api/v1/team_memberships", %{client: client} do
    assert {:ok, %ArchAstro.Types.TeamMembershipListResponse{}} =
             ArchAstro.V1.TeamMemberships.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1TeamMemberships.Params{}
             )
  end

  test "GET /api/v1/team_memberships returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.TeamMemberships.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1TeamMemberships.Params{}
             )
  end

  test "GET /api/v1/team_memberships returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.TeamMemberships.list(
               client,
               %ArchAstro.Types.Operations.GetApiV1TeamMemberships.Params{}
             )
  end

  test "DELETE /api/v1/team_memberships/{team_membership}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.TeamMemberships.delete(client, "test-value")
  end

  test "DELETE /api/v1/team_memberships/{team_membership} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.TeamMemberships.delete(client, "test-value")
  end

  test "DELETE /api/v1/team_memberships/{team_membership} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.TeamMemberships.delete(client, "test-value")
  end
end
