# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 01baa8407c06

defmodule ArchAstro.SDK.Contract.V1.TeamsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/teams", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1Teams.Response{}} =
             ArchAstro.SDK.V1.Teams.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1Teams.Params{}
             )
  end

  test "GET /api/v1/teams returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Teams.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1Teams.Params{}
             )
  end

  test "GET /api/v1/teams returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1Teams.Params{}
             )
  end

  test "GET /api/v1/teams returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.list(
               client,
               %ArchAstro.SDK.Types.Operations.GetApiV1Teams.Params{}
             )
  end

  test "POST /api/v1/teams", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Team{}} =
             ArchAstro.SDK.V1.Teams.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Teams.Input{name: "test-name"}
             )
  end

  test "POST /api/v1/teams returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Teams.Input{name: "test-name"}
             )
  end

  test "POST /api/v1/teams returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Teams.Input{name: "test-name"}
             )
  end

  test "POST /api/v1/teams returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.create(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1Teams.Input{name: "test-name"}
             )
  end

  test "POST /api/v1/teams/join_by_code", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Team{}} =
             ArchAstro.SDK.V1.Teams.join_by_code(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsJoinByCode.Input{}
             )
  end

  test "POST /api/v1/teams/join_by_code returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Teams.join_by_code(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsJoinByCode.Input{}
             )
  end

  test "POST /api/v1/teams/join_by_code returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.join_by_code(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsJoinByCode.Input{}
             )
  end

  test "POST /api/v1/teams/join_by_code returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.join_by_code(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsJoinByCode.Input{}
             )
  end

  test "POST /api/v1/teams/join_by_code returns 429" do
    client = ArchAstro.SDK.ContractSupport.error_client(429)

    assert {:error, %ArchAstro.SDK.Error{status: 429}} =
             ArchAstro.SDK.V1.Teams.join_by_code(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsJoinByCode.Input{}
             )
  end

  test "DELETE /api/v1/teams/{team}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.Teams.delete(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.delete(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.delete(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.delete(client, "test-value")
  end

  test "GET /api/v1/teams/{team}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Team{}} = ArchAstro.SDK.V1.Teams.get(client, "test-value")
  end

  test "GET /api/v1/teams/{team} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.get(client, "test-value")
  end

  test "GET /api/v1/teams/{team} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.get(client, "test-value")
  end

  test "GET /api/v1/teams/{team} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.get(client, "test-value")
  end

  test "PATCH /api/v1/teams/{team}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Team{}} =
             ArchAstro.SDK.V1.Teams.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeam.Input{}
             )
  end

  test "PATCH /api/v1/teams/{team} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeam.Input{}
             )
  end

  test "PATCH /api/v1/teams/{team} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeam.Input{}
             )
  end

  test "PATCH /api/v1/teams/{team} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeam.Input{}
             )
  end

  test "PATCH /api/v1/teams/{team} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.update(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeam.Input{}
             )
  end

  test "GET /api/v1/teams/{team}/artifacts", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamArtifacts.Response{}} =
             ArchAstro.SDK.V1.Teams.artifacts(client, "test-value")
  end

  test "GET /api/v1/teams/{team}/artifacts returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.artifacts(client, "test-value")
  end

  test "GET /api/v1/teams/{team}/artifacts returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.artifacts(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/invite", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.TeamInvite{}} =
             ArchAstro.SDK.V1.Teams.invite(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/invite returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.invite(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/invite returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.invite(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/invite returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.invite(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/invites", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamInvites.Response{}} =
             ArchAstro.SDK.V1.Teams.invites(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/invites returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.invites(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/invites returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.invites(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/join", %{client: client} do
    assert {:ok, :ok} =
             ArchAstro.SDK.V1.Teams.join(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamJoin.Input{}
             )
  end

  test "POST /api/v1/teams/{team}/join returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Teams.join(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamJoin.Input{}
             )
  end

  test "POST /api/v1/teams/{team}/join returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.join(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamJoin.Input{}
             )
  end

  test "POST /api/v1/teams/{team}/join returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.join(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamJoin.Input{}
             )
  end

  test "POST /api/v1/teams/{team}/join returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.join(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamJoin.Input{}
             )
  end

  test "DELETE /api/v1/teams/{team}/leave", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.Teams.leave(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/leave returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.leave(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/leave returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.leave(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/leave returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.leave(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/leave returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.leave(client, "test-value")
  end

  test "GET /api/v1/teams/{team}/task_assignees", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTaskAssignees.Response{}} =
             ArchAstro.SDK.V1.Teams.task_assignees(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTaskAssignees.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/task_assignees returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.task_assignees(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTaskAssignees.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/task_assignees returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.task_assignees(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTaskAssignees.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/task_assignees returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.task_assignees(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTaskAssignees.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/custom_objects", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamCustomObjects.Response{}} =
             ArchAstro.SDK.V1.Teams.CustomObjects.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamCustomObjects.Params{type: "test"}
             )
  end

  test "GET /api/v1/teams/{team}/custom_objects returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.CustomObjects.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamCustomObjects.Params{type: "test"}
             )
  end

  test "GET /api/v1/teams/{team}/custom_objects returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.CustomObjects.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamCustomObjects.Params{type: "test"}
             )
  end

  test "POST /api/v1/teams/{team}/custom_objects", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.CustomObject{}} =
             ArchAstro.SDK.V1.Teams.CustomObjects.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamCustomObjects.Input{
                 fields: %{},
                 type: "test"
               }
             )
  end

  test "POST /api/v1/teams/{team}/custom_objects returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.CustomObjects.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamCustomObjects.Input{
                 fields: %{},
                 type: "test"
               }
             )
  end

  test "POST /api/v1/teams/{team}/custom_objects returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.CustomObjects.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamCustomObjects.Input{
                 fields: %{},
                 type: "test"
               }
             )
  end

  test "POST /api/v1/teams/{team}/custom_objects returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.CustomObjects.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamCustomObjects.Input{
                 fields: %{},
                 type: "test"
               }
             )
  end

  test "DELETE /api/v1/teams/{team}/members", %{client: client} do
    assert {:ok, :ok} = ArchAstro.SDK.V1.Teams.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/members returns 400" do
    client = ArchAstro.SDK.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.SDK.Error{status: 400}} =
             ArchAstro.SDK.V1.Teams.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/members returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/members returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/teams/{team}/members returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Members.remove(client, "test-value")
  end

  test "GET /api/v1/teams/{team}/members", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamMembers.Response{}} =
             ArchAstro.SDK.V1.Teams.Members.list(client, "test-value")
  end

  test "GET /api/v1/teams/{team}/members returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Members.list(client, "test-value")
  end

  test "GET /api/v1/teams/{team}/members returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Members.list(client, "test-value")
  end

  test "POST /api/v1/teams/{team}/members", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.TeamMembership{}} =
             ArchAstro.SDK.V1.Teams.Members.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamMembers.Input{}
             )
  end

  test "POST /api/v1/teams/{team}/members returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Members.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamMembers.Input{}
             )
  end

  test "POST /api/v1/teams/{team}/members returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Members.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamMembers.Input{}
             )
  end

  test "POST /api/v1/teams/{team}/members returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Members.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamMembers.Input{}
             )
  end

  test "PATCH /api/v1/teams/{team}/members/{user}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.TeamMembership{}} =
             ArchAstro.SDK.V1.Teams.Members.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeamMembersUser.Input{role: "user"}
             )
  end

  test "PATCH /api/v1/teams/{team}/members/{user} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Members.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeamMembersUser.Input{role: "user"}
             )
  end

  test "PATCH /api/v1/teams/{team}/members/{user} returns 403" do
    client = ArchAstro.SDK.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.SDK.Error{status: 403}} =
             ArchAstro.SDK.V1.Teams.Members.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeamMembersUser.Input{role: "user"}
             )
  end

  test "PATCH /api/v1/teams/{team}/members/{user} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Members.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeamMembersUser.Input{role: "user"}
             )
  end

  test "PATCH /api/v1/teams/{team}/members/{user} returns 409" do
    client = ArchAstro.SDK.ContractSupport.error_client(409)

    assert {:error, %ArchAstro.SDK.Error{status: 409}} =
             ArchAstro.SDK.V1.Teams.Members.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeamMembersUser.Input{role: "user"}
             )
  end

  test "PATCH /api/v1/teams/{team}/members/{user} returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Members.update(
               client,
               "test-value",
               "test-value",
               %ArchAstro.SDK.Types.Operations.PatchApiV1TeamsTeamMembersUser.Input{role: "user"}
             )
  end

  test "GET /api/v1/teams/{team}/tasks", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasks.Response{}} =
             ArchAstro.SDK.V1.Teams.Tasks.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasks.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Tasks.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasks.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Tasks.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasks.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Tasks.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasks.Params{}
             )
  end

  test "POST /api/v1/teams/{team}/tasks", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Task{}} =
             ArchAstro.SDK.V1.Teams.Tasks.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input{
                 task: %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input.Nested.Task{
                   name: "test-name"
                 }
               }
             )
  end

  test "POST /api/v1/teams/{team}/tasks returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Tasks.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input{
                 task: %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input.Nested.Task{
                   name: "test-name"
                 }
               }
             )
  end

  test "POST /api/v1/teams/{team}/tasks returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Tasks.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input{
                 task: %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input.Nested.Task{
                   name: "test-name"
                 }
               }
             )
  end

  test "POST /api/v1/teams/{team}/tasks returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Tasks.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input{
                 task: %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamTasks.Input.Nested.Task{
                   name: "test-name"
                 }
               }
             )
  end

  test "GET /api/v1/teams/{team}/tasks/blocker_cycles", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksBlockerCycles.Response{}} =
             ArchAstro.SDK.V1.Teams.Tasks.blocker_cycles(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksBlockerCycles.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/blocker_cycles returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Tasks.blocker_cycles(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksBlockerCycles.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/blocker_cycles returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Tasks.blocker_cycles(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksBlockerCycles.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/blocker_cycles returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Tasks.blocker_cycles(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksBlockerCycles.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/metrics", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksMetrics.Response{}} =
             ArchAstro.SDK.V1.Teams.Tasks.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksMetrics.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/metrics returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Tasks.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksMetrics.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/metrics returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Tasks.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksMetrics.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/metrics returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Tasks.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksMetrics.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/search", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksSearch.Response{}} =
             ArchAstro.SDK.V1.Teams.Tasks.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksSearch.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/search returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Tasks.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksSearch.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/search returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Tasks.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksSearch.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/tasks/search returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Tasks.search(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamTasksSearch.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/threads", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreads.Response{}} =
             ArchAstro.SDK.V1.Teams.Threads.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreads.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/threads returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Threads.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreads.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/threads returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Threads.list(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreads.Params{}
             )
  end

  test "POST /api/v1/teams/{team}/threads", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Thread{}} =
             ArchAstro.SDK.V1.Teams.Threads.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/teams/{team}/threads returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Threads.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/teams/{team}/threads returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Threads.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input.Nested.Thread{}
               }
             )
  end

  test "POST /api/v1/teams/{team}/threads returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Threads.create(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input{
                 thread:
                   %ArchAstro.SDK.Types.Operations.PostApiV1TeamsTeamThreads.Input.Nested.Thread{}
               }
             )
  end

  test "GET /api/v1/teams/{team}/threads/metrics", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreadsMetrics.Response{}} =
             ArchAstro.SDK.V1.Teams.Threads.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreadsMetrics.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/threads/metrics returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Teams.Threads.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreadsMetrics.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/threads/metrics returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Teams.Threads.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreadsMetrics.Params{}
             )
  end

  test "GET /api/v1/teams/{team}/threads/metrics returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Teams.Threads.metrics(
               client,
               "test-value",
               %ArchAstro.SDK.Types.Operations.GetApiV1TeamsTeamThreadsMetrics.Params{}
             )
  end
end
