# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 5ce58b7b3fff

defmodule ArchAstro.Contract.V1.ThreadsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.ContractSupport.client()}
  end

  test "DELETE /api/v1/threads/{thread}", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Threads.delete(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.delete(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.delete(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.delete(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}", %{client: client} do
    assert {:ok, %ArchAstro.Types.Thread{}} = ArchAstro.V1.Threads.get(client, "test-value")
  end

  test "GET /api/v1/threads/{thread} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.Error{status: 401}} = ArchAstro.V1.Threads.get(client, "test-value")
  end

  test "GET /api/v1/threads/{thread} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)
    assert {:error, %ArchAstro.Error{status: 403}} = ArchAstro.V1.Threads.get(client, "test-value")
  end

  test "GET /api/v1/threads/{thread} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)
    assert {:error, %ArchAstro.Error{status: 404}} = ArchAstro.V1.Threads.get(client, "test-value")
  end

  test "PUT /api/v1/threads/{thread}", %{client: client} do
    assert {:ok, %ArchAstro.Types.Thread{}} =
             ArchAstro.V1.Threads.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThread.Input{}
             )
  end

  test "PUT /api/v1/threads/{thread} returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Threads.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThread.Input{}
             )
  end

  test "PUT /api/v1/threads/{thread} returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThread.Input{}
             )
  end

  test "PUT /api/v1/threads/{thread} returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThread.Input{}
             )
  end

  test "PUT /api/v1/threads/{thread} returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThread.Input{}
             )
  end

  test "PUT /api/v1/threads/{thread} returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThread.Input{}
             )
  end

  test "GET /api/v1/threads/{thread}/agents", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1ThreadsThreadAgents.Response{}} =
             ArchAstro.V1.Threads.agents(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/agents returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.agents(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/agents returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.agents(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/agents returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.agents(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/artifacts", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1ThreadsThreadArtifacts.Response{}} =
             ArchAstro.V1.Threads.artifacts(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/artifacts returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.artifacts(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/artifacts returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.artifacts(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/artifacts returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.artifacts(client, "test-value")
  end

  test "POST /api/v1/threads/{thread}/mark_read", %{client: client} do
    assert {:ok, :ok} =
             ArchAstro.V1.Threads.mark_read(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMarkRead.Input{}
             )
  end

  test "POST /api/v1/threads/{thread}/mark_read returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.mark_read(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMarkRead.Input{}
             )
  end

  test "POST /api/v1/threads/{thread}/mark_read returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.mark_read(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMarkRead.Input{}
             )
  end

  test "POST /api/v1/threads/{thread}/mark_read returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.mark_read(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMarkRead.Input{}
             )
  end

  test "GET /api/v1/threads/{thread}/messages", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1ThreadsThreadMessages.Response{}} =
             ArchAstro.V1.Threads.messages(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadMessages.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/messages returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Threads.messages(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadMessages.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/messages returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.messages(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadMessages.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/messages returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.messages(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadMessages.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/messages returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.messages(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadMessages.Params{}
             )
  end

  test "PUT /api/v1/threads/{thread}/picture", %{client: client} do
    assert {:ok, %ArchAstro.Types.Thread{}} =
             ArchAstro.V1.Threads.picture(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input{
                 picture:
                   %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input.Nested.Picture{
                     data: "test-value",
                     filename: "test-value",
                     mime_type: "application/json"
                   }
               }
             )
  end

  test "PUT /api/v1/threads/{thread}/picture returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.picture(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input{
                 picture:
                   %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input.Nested.Picture{
                     data: "test-value",
                     filename: "test-value",
                     mime_type: "application/json"
                   }
               }
             )
  end

  test "PUT /api/v1/threads/{thread}/picture returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.picture(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input{
                 picture:
                   %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input.Nested.Picture{
                     data: "test-value",
                     filename: "test-value",
                     mime_type: "application/json"
                   }
               }
             )
  end

  test "PUT /api/v1/threads/{thread}/picture returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.picture(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input{
                 picture:
                   %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input.Nested.Picture{
                     data: "test-value",
                     filename: "test-value",
                     mime_type: "application/json"
                   }
               }
             )
  end

  test "PUT /api/v1/threads/{thread}/picture returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.picture(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input{
                 picture:
                   %ArchAstro.Types.Operations.PutApiV1ThreadsThreadPicture.Input.Nested.Picture{
                     data: "test-value",
                     filename: "test-value",
                     mime_type: "application/json"
                   }
               }
             )
  end

  test "GET /api/v1/threads/{thread}/read_status", %{client: client} do
    assert {:ok, %ArchAstro.Types.ThreadReadStatus{}} =
             ArchAstro.V1.Threads.read_status(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadReadStatus.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/read_status returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.read_status(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadReadStatus.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/read_status returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.read_status(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadReadStatus.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/read_status returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.read_status(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadReadStatus.Params{}
             )
  end

  test "GET /api/v1/threads/{thread}/search", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Response{}} =
             ArchAstro.V1.Threads.search(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Params{q: "test-value"}
             )
  end

  test "GET /api/v1/threads/{thread}/search returns 400" do
    client = ArchAstro.ContractSupport.error_client(400)

    assert {:error, %ArchAstro.Error{status: 400}} =
             ArchAstro.V1.Threads.search(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Params{q: "test-value"}
             )
  end

  test "GET /api/v1/threads/{thread}/search returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.search(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Params{q: "test-value"}
             )
  end

  test "GET /api/v1/threads/{thread}/search returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.search(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Params{q: "test-value"}
             )
  end

  test "GET /api/v1/threads/{thread}/search returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.search(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Params{q: "test-value"}
             )
  end

  test "GET /api/v1/threads/{thread}/search returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.search(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Params{q: "test-value"}
             )
  end

  test "GET /api/v1/threads/{thread}/search returns 502" do
    client = ArchAstro.ContractSupport.error_client(502)

    assert {:error, %ArchAstro.Error{status: 502}} =
             ArchAstro.V1.Threads.search(
               client,
               "test-value",
               %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSearch.Params{q: "test-value"}
             )
  end

  test "DELETE /api/v1/threads/{thread}/members", %{client: client} do
    assert {:ok, :ok} = ArchAstro.V1.Threads.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/members returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/members returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/members returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Members.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/members returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.Members.remove(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/members", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1ThreadsThreadMembers.Response{}} =
             ArchAstro.V1.Threads.Members.list(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/members returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Members.list(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/members returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Members.list(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/members returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Members.list(client, "test-value")
  end

  test "POST /api/v1/threads/{thread}/members", %{client: client} do
    assert {:ok, %ArchAstro.Types.ChatMember{}} =
             ArchAstro.V1.Threads.Members.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMembers.Input{type: "test"}
             )
  end

  test "POST /api/v1/threads/{thread}/members returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Members.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMembers.Input{type: "test"}
             )
  end

  test "POST /api/v1/threads/{thread}/members returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Members.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMembers.Input{type: "test"}
             )
  end

  test "POST /api/v1/threads/{thread}/members returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Members.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMembers.Input{type: "test"}
             )
  end

  test "POST /api/v1/threads/{thread}/members returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.Members.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadMembers.Input{type: "test"}
             )
  end

  test "GET /api/v1/threads/{thread}/settings", %{client: client} do
    assert {:ok, %ArchAstro.Types.Operations.GetApiV1ThreadsThreadSettings.Response{}} =
             ArchAstro.V1.Threads.Settings.list(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/settings returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Settings.list(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/settings returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Settings.list(client, "test-value")
  end

  test "GET /api/v1/threads/{thread}/settings returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Settings.list(client, "test-value")
  end

  test "PUT /api/v1/threads/{thread}/settings", %{client: client} do
    assert {:ok, %ArchAstro.Types.ThreadSettings{}} =
             ArchAstro.V1.Threads.Settings.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadSettings.Input{settings: %{}}
             )
  end

  test "PUT /api/v1/threads/{thread}/settings returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Settings.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadSettings.Input{settings: %{}}
             )
  end

  test "PUT /api/v1/threads/{thread}/settings returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Settings.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadSettings.Input{settings: %{}}
             )
  end

  test "PUT /api/v1/threads/{thread}/settings returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Settings.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadSettings.Input{settings: %{}}
             )
  end

  test "PUT /api/v1/threads/{thread}/settings returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.Settings.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadSettings.Input{settings: %{}}
             )
  end

  test "DELETE /api/v1/threads/{thread}/tags", %{client: client} do
    assert {:ok, %ArchAstro.Types.Thread{}} = ArchAstro.V1.Threads.Tags.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/tags returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Tags.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/tags returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Tags.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/tags returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Tags.remove(client, "test-value")
  end

  test "DELETE /api/v1/threads/{thread}/tags returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.Tags.remove(client, "test-value")
  end

  test "POST /api/v1/threads/{thread}/tags", %{client: client} do
    assert {:ok, %ArchAstro.Types.Thread{}} =
             ArchAstro.V1.Threads.Tags.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "POST /api/v1/threads/{thread}/tags returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Tags.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "POST /api/v1/threads/{thread}/tags returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Tags.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "POST /api/v1/threads/{thread}/tags returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Tags.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "POST /api/v1/threads/{thread}/tags returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.Tags.create(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PostApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "PUT /api/v1/threads/{thread}/tags", %{client: client} do
    assert {:ok, %ArchAstro.Types.Thread{}} =
             ArchAstro.V1.Threads.Tags.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "PUT /api/v1/threads/{thread}/tags returns 401" do
    client = ArchAstro.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.Error{status: 401}} =
             ArchAstro.V1.Threads.Tags.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "PUT /api/v1/threads/{thread}/tags returns 403" do
    client = ArchAstro.ContractSupport.error_client(403)

    assert {:error, %ArchAstro.Error{status: 403}} =
             ArchAstro.V1.Threads.Tags.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "PUT /api/v1/threads/{thread}/tags returns 404" do
    client = ArchAstro.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.Error{status: 404}} =
             ArchAstro.V1.Threads.Tags.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadTags.Input{tags: []}
             )
  end

  test "PUT /api/v1/threads/{thread}/tags returns 422" do
    client = ArchAstro.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.Error{status: 422}} =
             ArchAstro.V1.Threads.Tags.replace(
               client,
               "test-value",
               %ArchAstro.Types.Operations.PutApiV1ThreadsThreadTags.Input{tags: []}
             )
  end
end
