# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
# This file is auto-generated by @archastro/sdk-generator. Do not edit.
# Content hash: 13bddb140df9

defmodule ArchAstro.SDK.Contract.V1.WorkflowsTest do
  use ExUnit.Case, async: false

  setup do
    {:ok, client: ArchAstro.SDK.ContractSupport.client()}
  end

  test "GET /api/v1/workflows/commands", %{client: client} do
    assert {:ok, items} = ArchAstro.SDK.V1.Workflows.commands(client)
    assert is_list(items)
  end

  test "GET /api/v1/workflows/commands returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.SDK.Error{status: 401}} = ArchAstro.SDK.V1.Workflows.commands(client)
  end

  test "GET /api/v1/workflows/llm.txt", %{client: client} do
    assert {:ok, %Req.Response{}} = ArchAstro.SDK.V1.Workflows.llm_txt(client)
  end

  test "GET /api/v1/workflows/llm.txt returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)
    assert {:error, %ArchAstro.SDK.Error{status: 401}} = ArchAstro.SDK.V1.Workflows.llm_txt(client)
  end

  test "POST /api/v1/workflows/run", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsRun.Response{}} =
             ArchAstro.SDK.V1.Workflows.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsRun.Input{}
             )
  end

  test "POST /api/v1/workflows/run returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsRun.Input{}
             )
  end

  test "POST /api/v1/workflows/run returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Workflows.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsRun.Input{}
             )
  end

  test "GET /api/v1/workflows/events/{name}/sample", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.Operations.GetApiV1WorkflowsEventsNameSample.Response{}} =
             ArchAstro.SDK.V1.Workflows.Events.sample(client, "test-name")
  end

  test "GET /api/v1/workflows/events/{name}/sample returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.Events.sample(client, "test-name")
  end

  test "GET /api/v1/workflows/events/{name}/sample returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Workflows.Events.sample(client, "test-name")
  end

  test "POST /api/v1/workflows/expressions/run", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ExpressionResult{}} =
             ArchAstro.SDK.V1.Workflows.Expressions.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsExpressionsRun.Input{}
             )
  end

  test "POST /api/v1/workflows/expressions/run returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.Expressions.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsExpressionsRun.Input{}
             )
  end

  test "POST /api/v1/workflows/expressions/run returns 422" do
    client = ArchAstro.SDK.ContractSupport.error_client(422)

    assert {:error, %ArchAstro.SDK.Error{status: 422}} =
             ArchAstro.SDK.V1.Workflows.Expressions.run(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsExpressionsRun.Input{}
             )
  end

  test "POST /api/v1/workflows/expressions/validate", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.ExpressionValidation{}} =
             ArchAstro.SDK.V1.Workflows.Expressions.validate(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsExpressionsValidate.Input{}
             )
  end

  test "POST /api/v1/workflows/expressions/validate returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.Expressions.validate(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsExpressionsValidate.Input{}
             )
  end

  test "POST /api/v1/workflows/graph/validate", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.GraphValidation{}} =
             ArchAstro.SDK.V1.Workflows.Graph.validate(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsGraphValidate.Input{graph: %{}}
             )
  end

  test "POST /api/v1/workflows/graph/validate returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.Graph.validate(
               client,
               %ArchAstro.SDK.Types.Operations.PostApiV1WorkflowsGraphValidate.Input{graph: %{}}
             )
  end

  test "GET /api/v1/workflows/node_types", %{client: client} do
    assert {:ok, items} = ArchAstro.SDK.V1.Workflows.NodeTypes.list(client)
    assert is_list(items)
  end

  test "GET /api/v1/workflows/node_types returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.NodeTypes.list(client)
  end

  test "GET /api/v1/workflows/node_types/{node_type}", %{client: client} do
    assert {:ok, %ArchAstro.SDK.Types.NodeType{}} =
             ArchAstro.SDK.V1.Workflows.NodeTypes.get(client, "test-value")
  end

  test "GET /api/v1/workflows/node_types/{node_type} returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.NodeTypes.get(client, "test-value")
  end

  test "GET /api/v1/workflows/node_types/{node_type} returns 404" do
    client = ArchAstro.SDK.ContractSupport.error_client(404)

    assert {:error, %ArchAstro.SDK.Error{status: 404}} =
             ArchAstro.SDK.V1.Workflows.NodeTypes.get(client, "test-value")
  end

  test "GET /api/v1/workflows/sample", %{client: client} do
    assert {:ok, %Req.Response{}} = ArchAstro.SDK.V1.Workflows.Sample.list(client)
  end

  test "GET /api/v1/workflows/sample returns 401" do
    client = ArchAstro.SDK.ContractSupport.error_client(401)

    assert {:error, %ArchAstro.SDK.Error{status: 401}} =
             ArchAstro.SDK.V1.Workflows.Sample.list(client)
  end
end
